### PR TITLE
Adding myself as member of func-writers

### PR DESCRIPTION
**Pull request by matzew**
# Changes

- adding `matzew` as member of `func-writers`

/kind <kind>

Fixes #

**Release Note**

```release-note

```

**Docs**

```docs

```

### CODE REVIEW

**Comment by ReToCode** [comment]
> Please run ./hack/update-codegen.sh. 

;)

**Comment by matejvasek** [comment]
PTAL @ReToCode @evankanderson @dprotaso

**Comment by ReToCode** [comment]
According to owners, needs approval from

/cc @knative/technical-oversight-committee

**Pull request merged**
