### PR TITLE
Add minimal SECURITY.md

### PR DESCRIPTION
**Pull request by evankanderson**
Implement the simpler "GitHub intake" SECURITY.md recommended in #258.

https://github.com/knative/community/pull/258#issuecomment-780830476

### CODE REVIEW

**Comment by evankanderson** [comment]
/assign @julz @richterdavid 

To make sure you're okay with this, then it should be easy to get steering to approve this while we work on #258 if we want.

**Review by julz — APPROVED** [review]
Yeah, better to have something simple, imperfect and _actually merged_ for now

/lgtm

**Comment by rhuss** [comment]
thanks !

/lgtm
/approve

**Comment by richterdavid** [comment]
Will this appear properly on knative.dev?

We'll want a version of https://github.com/knative-sandbox/.github/pull/11 that points to this.

**Comment by rhuss** [comment]
@knative/steering-committee I think we need one of you to stamp this PR, because it touches a top-level file.

**Comment by rhuss** [comment]
> Will this appear properly on knative.dev?

I don't know if this is picked up by the website build, but as this is a new file, I doubt that it will magically appear in the generated docs. Would it be possible to adapt the link to show directly to the markdown file in the github repo, i.e. https://github.com/knative/community/blob/main/SECURITY.md ?

**Review by vaikas — APPROVED** [review]
/lgtm

**Pull request merged**
