### PR TITLE
move enduser election doc to readme

### PR DESCRIPTION
**Pull request by csantanapr**
I had a problem finding this doc, and it was not consistent with the other election doc location.

### CODE REVIEW

**Review by lance — COMMENTED** [review]
Is there a need to keep enduser.md around? Why not just rename the file?

**Comment by csantanapr** [comment]
@lance 
>Is there a need to keep enduser.md around? Why not just rename the file?

To not have broken links, I used the URL to enduser.md in the announcements emails.

**Comment by lance** [comment]
> To not have broken links, I used the URL to enduser.md in the announcements emails.

Makes total sense then. Just checking. :)

**Review by lance — APPROVED** [review]
/lgtm

**Pull request merged**
