### PR TITLE
Add eventing-kogito repository to peribolos

### PR DESCRIPTION
**Pull request by lionelvillard**
Part of #737

### CODE REVIEW

**Review by ricardozanini — APPROVED** [review]
LGTM

**Review by evankanderson — COMMENTED** [review]
/lgtm
/approve

**Comment by lionelvillard** [comment]
```
{"component":"unset","file":"prow/cmd/peribolos/main.go:202","func":"main.main","level":"fatal","msg":"Configuration failed: failed to configure knative-sandbox teams: failed to update eventing-kogito Approvers members: failed to list 0(eventing-kogito Approvers) members: return code not 2XX: 404 Not Found","severity":"fatal","time":"2021-08-23T14:15:08Z"
```

Is this still needed, since we moved away from CODEOWNERS?

**Comment by lionelvillard** [comment]
@evankanderson WDYT about the comment above?

**Comment by evankanderson** [comment]
You don't need a group, but it _can by l be used for assignments or via expansion in owners files.

**Comment by lionelvillard** [comment]
oh I didn't realize I had the right to create the GitHub team. Did it.

**Pull request merged**
