### PR TITLE
Adding slinkydeveloper as Delivery WG lead

### PR DESCRIPTION
**Pull request by slinkydeveloper**
Requirements:

* [ ] Participant in the working group for at least 3 months, for example as scribe or approver.
* [ ] Recognized as having expertise in the group’s subject matter.
* [ ] Sponsored by the technical oversight committee.

Signed-off-by: Francesco Guardiani <francescoguard@gmail.com>

### CODE REVIEW

**Review by Harwayne — COMMENTED** [review]
/lgtm

**Review by antoineco — APPROVED** [review]
Not sure I have these powers but...

/lgtm

**Comment by evankanderson** [comment]
/lgtm
/approve

Since the TOC members seemed generally in favor of this at the last TOC meeting.

**Pull request merged**
