### PR TITLE
Add wzshiming to the members list

### PR DESCRIPTION
**Pull request by wzshiming**
We are using Knative as our serverless framework, expected PR can be test directly.
I apply to join the Knative organization. 
Here is my contribution.
https://github.com/knative-sandbox/kn-plugin-source-kafka/pulls?q=is%3Apr+author%3Awzshiming
https://github.com/knative/serving/pulls?q=is%3Apr+author%3Awzshiming

### CODE REVIEW

**Comment by wzshiming** [comment]
/assign @tcnghia
Hi, could you have time to take a look.

**Review by tcnghia — APPROVED** [review]
/lgtm

**Comment by wzshiming** [comment]
Ping @grantr

**Pull request merged**
