### PR TITLE
Add lionelvillard as Eventing working group lead

### PR DESCRIPTION
**Pull request by lionelvillard**
Adding lionelvillard as Eventing working group lead.

[Requirements](https://knative.dev/contributing/roles/#working-group-technical-lead):

[X] Recognized as having expertise in the group’s subject matter.

    Design and implementation of the apiserversource
    Design and implementation of the delivery feature
    Design and implementation of the parallel feature
    Numerous stability and reliability improvements 

[X] Approver for some part of the codebase for at least 3 months (approver for part of the codebase since Sep 24 (4mo+))

[X] Member for at least 6 months (joined in May 2019)

[X] Primary reviewer for 20 substantial PRs ([35](https://github.com/knative/eventing/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Amerged+-author%3Alionelvillard+commenter%3Alionelvillard+-label%3Asize%2FS+-label%3Asize%2FXS+-label%3Asize%2FM+))

[X] Reviewed or merged at least 50 PRs ([75 reviews](https://github.com/knative/eventing/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Amerged+-author%3Alionelvillard+commenter%3Alionelvillard+))

[ ] Sponsored by the technical oversight committee.

/cc @vaikas

### CODE REVIEW

**Comment by n3wscott** [comment]
/LGTM

Thanks for your hard work Lionel!!

**Comment by evankanderson** [comment]
/lgtm

/assign @bsnchan 

Since I don't think TOC is OWNERS for this file. (We should probably do a per-file OWNERS here.)

**Comment by matzew** [comment]
:tada:   

/lgtm

good work, @lionelvillard  !

**Pull request merged**
