### PR TITLE
add jberkus as member

### PR DESCRIPTION
**Pull request by vaikas**
Need to add jberkus as a member as per #734 so that @jberkus can be added as Owner for the SC elections directory.

-
-
-

/kind <kind>

Fixes #

**Release Note**

```release-note

```

**Docs**

```docs

```

### CODE REVIEW

**Comment by vaikas** [comment]
/hold
Hold to make sure @jberkus is ok with this so this doesn't get accidentally merged.

**Comment by jberkus** [comment]
oh!  sorry, didn't realize I needed to do anything.

/lgtm

**Pull request merged**
