### PR TITLE
Nominate vaikas for SC

### PR DESCRIPTION
**Pull request by mattmoor**
/hold
/assign @vaikas 

Ville, LMK when you have a chance to give some real words for why you want to run, but in the meantime I went with parody to get something posted before the deadline. 😉

### CODE REVIEW

**Comment by vagababov** [comment]
Lack of candidate picture is appalling.

**Comment by mattmoor** [comment]
image

**Comment by evankanderson** [comment]
I endorse this candidate, assuming that @vaikas accepts.

Some other words you could put in:

Ville has been a _community_ participant since the project has started. He's not just a technical maestro, but he's also been instrumental at bringing the community together. He doesn't necessarily show up in the limelight a lot, but he's checking in that things are going okay and helping new people feel included in the community.

**Comment by jberkus** [comment]
We need @vaikas to accept the nomination before we can make this real.  Please have him do it by Monday, thanks!

**Comment by mattmoor** [comment]
@jberkus yup, he's en route back from Finland this weekend and was on PTO at the tail end of last week, I'll poke him to at least "Ack" here, but he's seen it and Ack'd privately.

**Comment by vaikas** [comment]
Ack
Should I do a follow on PR to try to add something else to the deets?

**Comment by vaikas** [comment]
@jberkus Thanks in advance, what's the best way to move forward here? Merge this PR and massage it, or ?

**Comment by mattmoor** [comment]
Closing in favor of #367

**Pull request closed without merging**
