### PR TITLE
Remove vaikas as eventing wg lead

### PR DESCRIPTION
**Pull request by vaikas**
Inspired by #622 and given that I've been doing this for way longer than I had anticipated, I'll make room for other folks to lead the future Eventing efforts by removing myself as an Eventing WG lead.
I also think the timing is great given we're finalizing the 1.0 efforts and it will be a great time for new folks start figuring out what's next after the 1.0.

-
-
-

/kind <kind>

Fixes #

**Release Note**

```release-note

```

**Docs**

```docs

```

### CODE REVIEW

**Comment by n3wscott** [comment]
Thank you Ville for your leadership and willingness to do all the horrible jobs eventing presented, like finish all those unit tests marked `TODO(vikas):` 🤣 ❤️

**Comment by bsnchan** [comment]
Thank you for everything you've done in eventing (and more!)

/lgtm

**Comment by devguyio** [comment]
@vaikas eventing will always be your baby. Whether it exists or not, for me you're the emeritus WG lead of Eventing.

**Comment by csantanapr** [comment]
Thank you @vaikas for all your great leadership and for going beyond the call to do all sorts of tasks to get things moving forward!

**Comment by matzew** [comment]
@vaikas thanks for all the great work you did as the lead for Knative Eventing. You made a huge difference on this project!

**Pull request merged**
