### PR TITLE
Extend nominations deadline for SC election

### PR DESCRIPTION
**Pull request by dsimansk**
# Changes

- Extend nominations deadline

PTAL take a look if we want to move the whole schedule accordingly. Or we can vote on that in a follow-up as well. 

/cc @knative/steering-committee

### CODE REVIEW

**Comment by jberkus** [comment]
We'll need to update election.yaml file as well, with the new dates.

**Review by psschwei — COMMENTED** [review]
+1

**Review by evankanderson — COMMENTED** [review]
:+1:

This seems good to me.  I was out last week, but I think I know at least one more candidate who may apply.

**Comment by dsimansk** [comment]
> We'll need to update election.yaml file as well, with the new dates.

Thanks, updated!

**Comment by davidhadas** [comment]
+1

**Comment by dprotaso** [comment]
+1

**Comment by dsimansk** [comment]
+1 to explicitly confirm 5 SC votes

**Comment by jberkus** [comment]
Config file looks good.

**Comment by aliok** [comment]
+1

**Pull request merged**
