### PR TITLE
Add gab-satchi to eventing-rabbitmq approvers

### PR DESCRIPTION
**Pull request by gab-satchi**
# Changes
Add gab-satchi to eventing-rabbitmq approvers

### CODE REVIEW

**Comment by gabo1208** [comment]
/retest
cc @dprotaso @kvmware

**Comment by evankanderson** [comment]
Assuming that @gabo1208 's comment is an approval.

/lgtm
/approve

**Comment by evankanderson** [comment]
(It looks like the presubmit is not getting the access token it needs to talk to the GitHub API, so it may take a little while for this to propagate.)

We probably also need a Steering approver, because per-file approvals don't actually work.

**Pull request merged**
