### PR TITLE
SC 2022 self nomination for candidate smoser-ibm.md

### PR DESCRIPTION
**Pull request by smoser-ibm**
# Changes

-
-
-

/kind <kind>

Fixes #

**Release Note**

```release-note

```

**Docs**

```docs

```

### CODE REVIEW

**Comment by geekygirldawn** [comment]
/hold
Holding for validation of file format and eligibility verification

**Comment by jberkus** [comment]
Format is valid.  

/lgtm

Not removing hold because we need to validate eligibility.

**Comment by geekygirldawn** [comment]
I've confirmed that @smoser-ibm meets the criteria to run for SC:
* Is an eligible voter in this election (confirmed in voters.yaml)
* Holds at least a project member role (is an org member and Trademark Committee member)

/hold cancel
/approve

**Pull request merged**
