### PR TITLE
Added cali0707 as eventing reviewer

### PR DESCRIPTION
**Pull request by Cali0707**
# Changes

- Add @Cali0707 as eventing reviewer
- Create eventing-kafka-broker-reviewer role
- Add @Cali0707 as eventing kafka broker reviewer

### CODE REVIEW

**Comment by creydr** [comment]
```
knative/community is out of date. Please run hack/update-codegen.sh
```

**Review by pierDipi — COMMENTED** [review]
We need to create GH group like https://github.com/knative/community/blob/625ea8e2d64400f75340d51024d8167d50fbe751/peribolos/knative.yaml#L425-L430

**Comment by pierDipi** [comment]
From there the `hack/update-codegen.sh` will generate owner aliases

**Pull request merged**
