### PR TITLE
Added new IBM zSystems maintainer for knative projects

### PR DESCRIPTION
**Pull request by haubenr**
# Changes

This PR adds a new member to knative and knative-sandbox projects: Dilip Bhagavan (dilipgb)
Dilip will be my successor as the primary maintainer for the IBM zSystems (aka s390x) platform. I will phase out of this role shortly (once that happens, another PR removing my ID from the member lists will follow).

### CODE REVIEW

**Comment by psschwei** [comment]
@dilipgb can you confirm?

**Comment by dilipgb** [comment]
@psschwei I confirm, please add me to contributors. Thanks!

**Review by psschwei — COMMENTED** [review]
/lgtm
/assign @dprotaso @evankanderson  
for approval from non-IBMer

**Pull request merged**
