### PR TITLE
Add creydr as a knative and knative-sandbox member

### PR DESCRIPTION
**Pull request by creydr**
Adding myself as a knative and knative-sandbox member so I don't have to wait for the `ok-to-test` labels.

Contributions so far:
* [knative/docs](https://github.com/knative/docs/issues?q=author%3Acreydr)
* [knative/eventing](https://github.com/knative/eventing/issues?q=author%3Acreydr)

### CODE REVIEW

**Review by pierDipi — APPROVED** [review]
/lgtm

/cc @knative/technical-oversight-committee

**Review by evankanderson — COMMENTED** [review]
/lgtm
/approve

**Comment by creydr** [comment]
Pod timeouts reported in Slack productivity channel (https://knative.slack.com/archives/CCSNR4FCH/p1668609773470199)

**Comment by upodroid** [comment]
/retest

Prow failures have been fixed.

**Pull request merged**
