### PR TITLE
Fix formatting in Scott Nichol's profile for Elekto.

### PR DESCRIPTION
**Pull request by jberkus**
Some extra characters in Scott's profile are giving Elekto indigestion.  This PR fixes them.

### CODE REVIEW

**Comment by jberkus** [comment]
@bsnchan @pmorie @thisisnotapril please approve, thanks!

**Comment by n3wscott** [comment]
that title is next level trolling 🤣

**Comment by n3wscott** [comment]
I ran my linter on the original PR and I think it really garbled that header... 🙄

**Comment by jberkus** [comment]
@n3wscott oops.  Fixing ...

**Comment by jberkus** [comment]
Hey, can we get a merge here? Voters are locked out of the election until it merges.

**Pull request merged**
