### PR TITLE
membership: add sadath-12

### PR DESCRIPTION
**Pull request by sadath-12**
# Changes

Add @sadath-12 as a member to the community since he has been working on fixing issues and raising pr's https://github.com/pulls?q=is%3Apr+author%3Asadath-12+archived%3Afalse+knative%2Feventing+ and is active in the community . 
He wants to continue this journey with knative 

/kind <kind>

Fixes #

**Release Note**

```release-note

```

**Docs**

```docs

```

### CODE REVIEW

**Comment by ReToCode** [comment]
cc @creydr @pierDipi

**Review by creydr — COMMENTED** [review]
LGTM from my side. Thanks @sadath-12 for your contributions so far and your support in the community.

/lgtm

**Pull request merged**
