### PR TITLE
Add Gojek to list of Adopters

### PR DESCRIPTION
**Pull request by krithika369**
# Changes

- Adding Gojek to the list of adopters. We, in the Data Science Platform team, use Knative Serving extensively.

/kind

Fixes #

**Release Note**

```release-note

```

**Docs**

```docs

```

### CODE REVIEW

**Comment by dprotaso** [comment]
/lgtm
/approve

You'll need to sign the CLA - follow the instructions here - https://github.com/knative/community/pull/1338#issuecomment-1533230663

**Comment by dprotaso** [comment]
/unassign @dprotaso 

This needs to be approved by @knative/steering-committee

**Comment by lance** [comment]
@krithika369 can you please sign the CLA? We will need that to land this commit. Thanks!

/assign

**Comment by krithika369** [comment]
Hey @lance, I've signed the CLA now (and had to force-push the branch to get the check to pass). LMK if anything else is required. Thanks!

**Pull request merged**
