### PR TITLE
Add knative/.artifacthub repository

### PR DESCRIPTION
**Pull request by dsimansk**
Adding a new repository per issue https://github.com/knative/community/issues/1258.

Hold for TOC approval. 
/hold

### CODE REVIEW

**Comment by psschwei** [comment]
org / reponame are still under discussion in the linked issue

**Comment by dsimansk** [comment]
@psschwei I've updated the name per discussion on the issue.

**Review by psschwei — COMMENTED** [review]
/lgtm
/approve
/hold cancel

**Pull request merged**
