### PR TITLE
Remove test and to-import repo from peribolos

### PR DESCRIPTION
**Pull request by evankanderson**
Also rerun ./hack/update-autogen.sh, until Evan gets around to automating it.

### CODE REVIEW

**Review by rhuss — COMMENTED** [review]
/lgtm
/approve

**Comment by rhuss** [comment]
@knative/steering-committee the PR touches a top-level file as well.

Also, there are some other changes in the peribolos file, so maybe we need an other run to regenerate the top-level aliases ?

Automation would be cool as this would also free us ping steering everytime a change in the peribolos config happens.

**Comment by evankanderson** [comment]
Yeah, automation is on my list, probably after https://github.com/knative-sandbox/knobots/issues/94

**Comment by rhuss** [comment]
@evankanderson could you please re-run the script and update the PR ? That has been two updates earlier today to the peribolos config, so would be cool to get that in in one go.

**Review by evankanderson — COMMENTED** [review]
Updated! So long, Slinky, and thanks for all the 🐟 !

**Pull request merged**
