### PR TITLE
Add myself to the community

### PR DESCRIPTION
**Pull request by xtreme-vikram-yadav**
Addin myself to the Knative community members list

### CODE REVIEW

**Comment by csantanapr** [comment]
/hold
According to our process an already member need to open the PR to invite you, and the PR should have some info on how the individual meets the requirements.
Here are the docs https://github.com/knative/community/blob/main/ROLES.md#requirements

@xtreme-vikram-yadav if you could work with someone on the community to articulate how you meet the requirements that would be a great to move forward on joining.

**Comment by dprotaso** [comment]
I'm sponsoring this membership - @xtreme-vikram-yadav works on the VMware product packaging Knative and will start contributing upstream via code reviews/prs etc.

**Review by psschwei — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
