### PR TITLE
Update release leads for 1.2 release

### PR DESCRIPTION
**Pull request by nak3**
As per title.

/cc @dprotaso @psschwei @matzew 

The next release leads are Dave & Paul as per https://github.com/knative/release#schedule

### CODE REVIEW

**Review by rhuss — COMMENTED** [review]
/approve
/lgtm

Thanks for driving this 1.1 release @nak3 @matzew !

**Comment by nak3** [comment]
@rhuss sorry for bothering you. But could you please `/lgtm` again? I rebased.

**Comment by nak3** [comment]
This needs steering-committee's approval :sweat: 

/cc @lance @csantanapr

**Comment by nak3** [comment]
Tank you @lance @csantanapr 
I wonder we need your `/approve` rather than `/lgtm` :thinking:

**Pull request merged**
