### PR TITLE
extend to .23, remove v1beta1 eventing in .23

### PR DESCRIPTION
**Pull request by vaikas**
Add the next two releases .22 and .23 to the calendar. As per https://github.com/knative/eventing/issues/4836 also mark the eventing v1beta1 APIs as removed then.

-
-
-

/kind <kind>

Fixes #

**Release Note**

```release-note

```

**Docs**

```docs

```

### CODE REVIEW

**Review by rhuss — COMMENTED** [review]
Looks good , but I wonder about the minimum K8s release version.

According to the [K8s versioning principles](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/release/versioning.md), only the last 3 K8s minor versions are supported:

> Furthermore, we expect to "support" three minor releases at a time. "Support" means we expect users to be running that version in production, though we may not port fixes back before the latest minor version. For example, when v1.3 comes out, v1.0 will no longer be supported: basically, that means that the reasonable response to the question "my v1.0 cluster isn't working," is, "you should probably upgrade it, (and probably should have some time ago)". With minor releases happening approximately every three months, that means a minor release is supported for approximately nine months.

Then, K8s 1.21 is due to [April 8th](https://www.kubernetes.dev/resources/release/). So I wonder whether we shouldn't increase the minimal k8s version to 1.19 for Knative 0.22 (to be released on April 6th) ?

**Comment by vaikas** [comment]
@rhuss Thanks, yeah, was actually wondering about that as well. I was curious though about the fact that we only supported .18 for one release (.21) and then dropped the support. @dprotaso I recall you have been doing some digging into the k8s version support in the past, thoughts? I have no problem changing.

**Review by n3wscott — COMMENTED** [review]
/lgtm
/approve

**Comment by dprotaso** [comment]
Our K8s min principle states
> We (the community) support the range of upstream minor Kubernetes versions that are Kubernetes community supported at the time of the cut. 

1.18 isn't EOL'd until 2021-04-30: see https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md


Also 0.23.x should be 1.19.x

**Comment by dprotaso** [comment]
see: https://github.com/knative/community/issues/245#issuecomment-718316003

**Comment by vaikas** [comment]
Great, thanks. Updated, @dprotaso look good now?

**Review by mattmoor — APPROVED** [review]
/lgtm

**Pull request merged**
