### PR TITLE
Add msalatino (salaboy) as a TOC candidate

### PR DESCRIPTION
**Pull request by salaboy**
Hi everyone! 
My name is Mauricio Salatino (aka salaboy), I am working for VMware full time on the Knative OSS project. 
I would like to apply for candidacy as I am interested in growing the Knative community and keep driving new initiatives to cover new use cases, such as workflows, streaming and an improved functions experience. 

If you want to support my candidacy please add a comment here in the PR.

### CODE REVIEW

**Comment by geekygirldawn** [comment]
/hold
Putting a hold to make sure this doesn't get accidentally merged until after the nomination period closes so that people can continue to comment / endorse on this PR.

Verified that Mauricio is an approver meets the qualification as a candidate.

**Comment by gabo1208** [comment]
Mauricio have been driving a lot on the Eventing and Functions side of the project, is a pleasure working with him personally. I fully endorse this candidacy :)!

**Comment by kvmware** [comment]
Mauricio outreach and presentations skills are fantastic to have for the knative communit!

**Comment by xtreme-sameer-vohra** [comment]
Mauricio has had a solid impact streak during his tenure on the Knative project and I think he'd be great for the Knative community as part of the TOC.
Besides the `func` work, Mauricio was also very involved in rallying the community behind the 1.0/GA milestone last year including some of the humbling conformance efforts.

**Comment by aamonten** [comment]
I support Mauricio, he is doing amazing things for the community

**Comment by carlisia** [comment]
A bit late but wanted to comment anyway: Mauricio is both a strong technical lead and very vested that Knative serves as a wide audience as possible. He has my full support!

**Pull request merged**
