### PR TITLE
Specs repo peribolos changes + Conformance WG

### PR DESCRIPTION
**Pull request by tayarani**
# Changes

-
-
-

/kind <kind>

Fixes # https://github.com/knative/community/issues/499

**Release Note**

```release-note

```

**Docs**

```docs

```

### CODE REVIEW

**Comment by vaikas** [comment]
Looks like conformance writers does not exist:

```
{"component":"unset","file":"prow/cmd/peribolos/main.go:202","func":"main.main","level":"fatal","msg":"Configuration failed: failed to configure knative teams: failed to update Conformance Writers members: failed to list 0(Conformance Writers) members: return code not 2XX: 404 Not Found","severity":"fatal","time":"2021-02-26T22:36:24Z"}
```

**Comment by tayarani** [comment]
@vaikas the failure is due to the Conformance Writers team not existing here: https://github.com/orgs/knative/teams

I don't have permission to create it. Can someone create it for me?

**Comment by tayarani** [comment]
cc @grantr

**Comment by vaikas** [comment]
@tayarani created the team, retrying now.
/retest

**Comment by vaikas** [comment]
Hm, still fails:
```

{"component":"unset","file":"prow/cmd/peribolos/main.go:202","func":"main.main","level":"fatal","msg":"Configuration failed: failed to configure knative-sandbox teams: failed to update Conformance Writers members: failed to list 0(Conformance Writers) members: return code not 2XX: 404 Not Found","severity":"fatal","time":"2021-03-01T16:39:47Z"}
```

But, I did create the team here:
https://github.com/orgs/knative/teams/conformance-writers

I didn't realize I also needed to (looks like) create it in the knative-sandbox. Did that, retrying.
/retest

**Comment by vaikas** [comment]
And for the knative repo, looks like we need to create this group also:
Conformance WG Leads

**Comment by vaikas** [comment]
Ok, created those teams as children.
/retest

**Comment by tayarani** [comment]
Looks like that worked. Thanks @vaikas!

**Pull request merged**
