### PR TITLE
Archive knative-extensions/net-certmanager repository

### PR DESCRIPTION
**Pull request by ReToCode**
# Changes
- Archive knative-extensions/net-certmanager repository

Partially https://github.com/knative/community/issues/1563

### CODE REVIEW

**Comment by skonto** [comment]
LGTM

**Comment by skonto** [comment]
cc @davidhadas @dsimansk

**Comment by dprotaso** [comment]
Hey - we technically shouldn't archive net-certmanager until v1.14 and v1.13 has EOL. Which is Oct ([ref](https://github.com/knative/community/blob/main/mechanics/RELEASE-SCHEDULE.md#releases-supported-by-community))

This is in case we neet to cut a point release

**Comment by ReToCode** [comment]
I see, just wanted to make sure no changes happen by accident. As it's already done, let's undo it when needed.

**Pull request merged**
