### PR TITLE
Add a team for kperf approvers

### PR DESCRIPTION
**Pull request by mattmoor**
cc @zhanggbj @maximilien 
/cc @knative/technical-oversight-committee

### CODE REVIEW

**Comment by vaikas** [comment]
Does the team need to be created first?
```

{"component":"unset","file":"prow/cmd/peribolos/main.go:202","func":"main.main","level":"fatal","msg":"Configuration failed: failed to configure knative-sandbox teams: failed to update kperf Approvers members: failed to list 0(kperf Approvers) members: return code not 2XX: 404 Not Found","severity":"fatal","time":"2021-02-22T19:56:14Z"}
```

**Comment by mattmoor** [comment]
@vaikas yeah, it'll block submit.  I will create it now and `/retest`, but wanted eyeballs on it first.

**Pull request merged**
