### PR TITLE
Add Zbynek as TOC candidate

### PR DESCRIPTION
**Pull request by zroubalik**
Hi, I am Zbynek Roubalik (Zbyněk Roubalík if you fancy Czech diacritics). 

My main focus have been around Functions on Knative, ie. some initial not so successful attempts, then Boson project, that later became Knative Sandbox project (`func` kn plugin) and is now on it's way to become a full-fledged Working Group, yay!
The other area of my interest is around KEDA & Knative integration, which initally enabled autoscaling of a few Eventing Sources
and has a great potential to be expanded even more. This really makes even the Knative infrastructure serverless.

I think that I am able to openly to listen to other peoples thoughts/ideas and I'd define myself as result driven - I just love seeing getting things done.
I am also a maintainer of another CNCF project - KEDA, which is fairly smaller in comparison to Knative,
though I think that I can bring some inputs and ideas from this area (and a little bit different user community) as well.
I think that Knative is a great project and we all should focus on making it even more accessible for new users and potential contributors.
The internal technical goodies of any project are great, though I think that aeveloper accessibility and usability is a key area.

And yes, I think that this Steve's quote is valid more than ever 😃
https://c.tenor.com/xJSM2Ky3WpgAAAAM/steve-ballmer-microsoft.gif

### CODE REVIEW

**Comment by geekygirldawn** [comment]
/hold
Putting a hold to make sure this doesn't get accidentally merged until after the nomination period closes so that people can continue to comment / endorse on this PR.

Verified that Zbyněk is an approver for Knative Sandbox projects, so he meets the qualification as a candidate.

**Comment by aslom** [comment]
I have worked with Zbynek for long time and I can confirm that he is great to work as he is open to inputs, great listener, and focused on getting things done. I am especially looking forward to his goals about developer accessibility and usability as key areas as I think that is what Knative needs for future growth and longterm success of the project.

**Pull request merged**
