### PR TITLE
adding murugappan as candidate for sc

### PR DESCRIPTION
**Pull request by itsmurugappan**
Filing my nomination for sc seat

At Optum, I have been instrumental in adopting Knative at an early stage and making it into a preferred 
platform for developers to deploy apps. We were able to achieve this by consistently 
engaging with the Knative community, sharing our feedback and raising issues/pull requests. 

Knative has just become GA and has a long way to go. I want to be part of this journey and provide 
an end user perspective to the future road maps and encourage more active participation of end users.

### CODE REVIEW

**Comment by geekygirldawn** [comment]
Hi @itsmurugappan! I need to clarify whether you are running for the SC in general (you seem to be eligible), and if so, this is the correct process.

However, if you want to be considered for the end user seat, there will be a separate process for that (to be announced after this election). The newly elected steering committee for the current election will be selecting someone for the end user seat separately. 

If you want to be considered by the new SC for the end user seat, please close this PR. 

If you are running in the main SC election, let me know, and I can merge this PR.

**Comment by itsmurugappan** [comment]
@geekygirldawn thanks for the information. I would like to run for the main SC election.

**Comment by csantanapr** [comment]
I think @itsmurugappan would be great for the new SC for the end user seat
Would be awsome to have our first end-user representation on the SC

**Comment by csantanapr** [comment]
@geekygirldawn what's the process to get @itsmurugappan into the SC as an end-user, there should not be any voting right?

**Comment by geekygirldawn** [comment]
@csantanapr Since @itsmurugappan has enough contributions on his own, he can run for a regular contributing seat, which are open to any project contributor, which is what he requested in the comments above. With that said, if @itsmurugappan is not elected, it is still possible to be considered for the end user seat. The end user seat will be appointed by the newly elected steering committee using a process that they deem appropriate - to be announced after the new SC is in place.

**Comment by vaikas** [comment]
@itsmurugappan Would you mind creating a new PR in the EUC directory?

**Comment by itsmurugappan** [comment]
sure @vaikas

**Pull request merged**
