### PR TITLE
Add Ahmed Abdalla as Eventing WG execution lead

### PR DESCRIPTION
**Pull request by devguyio**
[Requirements](https://knative.dev/community/contributing/roles/#requirements-3):

- [x] **Participant in the working group for at least 3 months, for example as scribe or approver.**
 
  - Been involved in the working group since June, 2018
- [x] **Recognized as having expertise in the group’s subject matter.**
  - Was heavily involved in the inception of the Broker / Trigger APIs
    - Helped the WG get through a discussion bottleneck via suggesting a decision making process (e.g [this decision](https://docs.google.com/spreadsheets/d/14uj8A3NzGhHzCbcRbVnLItHhRytct09M9jxRGykrhcw/edit#gid=0))
    - Lead the first adoption of the Broker/Trigger APIs [in a GA release](https://kyma-project.io/blog/2020/3/31/release-notes-111/#eventing) 
  - Eventing working group improvement initiatives
    - [Knative Eventing WG Planning & Execution Analysis](https://docs.google.com/document/d/1XMdVsD6bkU2qd4JV2UUWM8Hmc5DTc4V1Jgt3m_gHb6I/edit#heading=h.67wupjiy2z3y )
    - Eventing WG [retrospective](https://funretro.io/publicboard/xYJrkNyhBrOrFvowHSCj7PrTpVQ2/5f65793b-9976-4758-bb0b-c67d240d8867)
    - [Enhanced testing task force](https://docs.google.com/document/d/1XHiL0hGY4gzI6Q8bvciB9X4OoOqNravrXby0zND3Rig/edit)
- [x] **Sponsored by the technical oversight committee.**

### CODE REVIEW

**Comment by evankanderson** [comment]
(Needs opinions from the above-mentioned WG leads before the TOC will approve it)

**Comment by evankanderson** [comment]
Note that thumbs-up emoji do not have an entry in the PR log (and so grantr@ could remove his thumbs-up after the PR submits and we'd all wonder why we approved this).

Emoji are also welcome, but it's nice to have a written record for the next issue that gets raised.

**Comment by vaikas** [comment]
I whole heartedly support this. The kinds of things that @devguyio has been doing are what I was hoping that our execution WG lead would be handling, and he's been driving several of these efforts. And as mentioned, there's a good track record of doing many tasks for awhile now.
My only thought is that since this is the first Execution WG lead, I want to make sure that we establish a solid baseline for future PRs to ensure we have consistency in the process. As long as folks feel that we're setting a solid precedence, I'm happy.

**Comment by lionelvillard** [comment]
I just want to underline what @vaikas already said. @devguyio is already assuming the role of an execution lead, albeit unofficially, by driving the discussions around the roadmap, organizing retrospectives and putting weekly reminders on the slack channel (among many other things). There is a lot more to do (feature tracks, I'm looking at you) and I'm quite confident @devguyio is up to the task. 

One last thing: as the first execution lead, the entire Knative community will be looking at you @devguyio. No pressure :-)

**Comment by grantr** [comment]
I agree with @vaikas and @lionelvillard, and want to add my 2 cents: an execution lead's job is more than writing roadmaps and meeting notes (though those things are important too). They also need to understand the humans in the community, their motivations, concerns, fears, goals, and communicate that understanding to others.

I've always been impressed by @devguyio's empathy to everyone and nuanced commentary describing his thoughts and others'. He really cares deeply about this community and its humans. I have confidence that as an execution lead, @devguyio will be a role model for how to keep the community healthy and productive by listening to each other and building shared understanding.

/lgtm

**Comment by mattmoor** [comment]
🎉 

Welcome @devguyio!

**Pull request merged**
