### PR TITLE
adding steven0711dong to knative and knative sandbox members

### PR DESCRIPTION
**Pull request by steven0711dong**
I'm working on Knative eventing at IBM.

Update knative-sandbox.yaml: Add steven0711dong
Add to the members list

Update knative.yaml: Add steven0711dong
Add to members list

### CODE REVIEW

**Comment by steven0711dong** [comment]
@googlebot I signed my cla

**Comment by steven0711dong** [comment]
@googlebot I signed it

**Comment by steven0711dong** [comment]
@googlebot I signed it!

**Comment by steven0711dong** [comment]
@googlebot I signed it!

**Comment by steven0711dong** [comment]
@googlebot I signed it!

**Comment by steven0711dong** [comment]
@googlebot I signed it!

**Review by tcnghia — APPROVED** [review]

**Pull request merged**
