### PR TITLE
Make David Simansky a Client WG Lead

### PR DESCRIPTION
**Pull request by rhuss**
# Changes

Make David Simansky a WG lead for the Knative client.

Criteria:

> Recognized as having expertise in the group’s subject matter.

David was the [main contributor to the client repository over the last 6 months](https://docs.google.com/presentation/d/14DkHunyVXuDrM9PLx1XLz5W9z613QWSeZKXRQUcxZw0/edit?usp=sharing).

> Approver for a relevant part of the codebase for at least 3 months.

David is an approver since [March 9th, 2021](https://github.com/knative/client/commit/9fa8d6b96eb035275462e39b51e42762c6acf82b#diff-c393dd2b18a8a597d895940893e574d6895122c4bf3ce6e2a78dbd9ca0cdd66f)

> Member for at least 6 months.

David is a Knative member for over a year.

> Primary reviewer for 20 substantial PRs.

  * [is:pr assignee:dsimansk is:closed label:size/M](https://github.com/knative/client/pulls?q=is%3Apr+assignee%3Adsimansk+is%3Aclosed+label%3Asize%2FM) == 18
  * [is:pr assignee:dsimansk is:closed label:size/L](https://github.com/knative/client/pulls?q=is%3Apr+assignee%3Adsimansk+is%3Aclosed+label%3Asize%2FL) == 12
  * [is:pr assignee:dsimansk is:closed label:size/XL](https://github.com/knative/client/pulls?q=is%3Apr+assignee%3Adsimansk+is%3Aclosed+label%3Asize%2FXL) == 3
  
> Reviewed or merged at least 50 PRs.

[75 assigned PRs](https://github.com/knative/client/pulls?q=type%3Apr+assignee%3Adsimansk+) as of creation of this PR.

> Sponsored by the technical oversight committee.

to be decided.

### CODE REVIEW

**Comment by navidshaikh** [comment]
+1

**Review by vaikas — COMMENTED** [review]
/lgtm
/approve

**Comment by rhuss** [comment]
@vaikas thanks for merging ! But my bad, I forgot to add `/hold` as the approval from the TOC was still missing.

@knative/technical-oversight-committee do you want me to send a rollback PR or could we quickly vote on this PR in retrospect?

**Comment by rhuss** [comment]
btw, +1 from my side :-)

**Comment by markusthoemmes** [comment]
+1 from my side (disclaimer: Red Hat affiliation etc etc), David is a breeze to work with and I'm sure he'll do a great job as WG lead

**Comment by julz** [comment]
+1 from me :)

**Comment by dprotaso** [comment]
+1

**Comment by evankanderson** [comment]
LGTM

**Comment by rhuss** [comment]
Perfect, thanks ! Going to add David now to the WORKING_GROUPS.md (which I forgot)

**Pull request merged**
