### PR TITLE
Replace SVG logo with embedded PNG by proper SVG

### PR DESCRIPTION
**Pull request by sisp**
# Changes

I've replaced the previous SVG logo that was actually just an embedded PNG image by a proper SVG image. The SVG is derived from the file [`knative-logo-rgb.ai`](https://github.com/knative/docs/blob/d14035d167c7eeeee1f63169d724bee725a05179/docs/images/logo/rgb/knative-logo-rgb.ai).

Related to https://github.com/knative/community/pull/669#discussion_r664051253.

/kind enhancement

### CODE REVIEW

**Comment by sisp** [comment]
I just noticed that the color values in the `.ai`/`.png`/... files disagree with the style guide. I've updated the colors according to the style guide in the SVG logo.

**Comment by vaikas** [comment]
@n3wscott PTAL

**Pull request merged**
