### PR TITLE
move eallred-google to org member

### PR DESCRIPTION
**Pull request by vaikas**
Addresses fallout from #425

Details for why this appears to be necessary:
https://github.com/knative/test-infra/issues/2652

And in particular this from prow logs:
```
{"component":"unset","file":"prow/cmd/peribolos/main.go:202","func":"main.main","level":"fatal","msg":"Configuration failed: failed to configure knative members: all team members/maintainers must also be org members: eallred-google","severity":"fatal","time":"2021-02-04T08:38:16Z"}

```

-
-
-

/kind <kind>

Fixes #

**Release Note**

```release-note

```

**Docs**

```docs

```

### CODE REVIEW

**Review by markusthoemmes — APPROVED** [review]
/lgtm
/approve

**Comment by markusthoemmes** [comment]
/hold

Is it intentional to remove from the actual group?

**Comment by vaikas** [comment]
Yes.

**Comment by markusthoemmes** [comment]
/unhold

seen the description in the issue.

**Pull request merged**
