### PR TITLE
Add missing word

### PR DESCRIPTION
**Pull request by lionelvillard**

### CODE REVIEW

**Review by rhuss — COMMENTED** [review]
/approve
/lgtm

**Comment by dsimansk** [comment]
Thanks!

/approve
/lgtm

**Review by zroubalik — APPROVED** [review]
/lgtm
/approve

**Comment by lionelvillard** [comment]
Only someone from the @knative/steering-committee can approve.

**Review by itsmurugappan — APPROVED** [review]
/lgtm

**Pull request merged**
