### PR TITLE
Ali Ok running for Knative SC election

### PR DESCRIPTION
**Pull request by aliok**
Ali Ok running for Knative SC election

### CODE REVIEW

**Comment by aliok** [comment]
cc election officers @ReToCode @geekygirldawn

**Comment by ReToCode** [comment]
I've confirmed that @aliok is [eligible as a candidate](https://github.com/knative/community/blob/main/mechanics/SC.md#candidate-eligibility) for the SC election.

I also looked at the format of the candidate file, and it looks good to me.

cc @geekygirldawn

**Comment by nainaz** [comment]
I endorse this! 
@aliok would be an excellent addition :)

**Comment by jberkus** [comment]
File formatting and naming is correct.

**Review by ReToCode — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
