### PR TITLE
Add Github team for ux-wg-leads

### PR DESCRIPTION
**Pull request by csantanapr**
# Changes

Adds a Github team `@knative/ux-wg-leads` 

Related to #466

### CODE REVIEW

**Comment by csantanapr** [comment]
cc @knative/technical-oversight-committee

**Comment by csantanapr** [comment]
/assign @evankanderson 

Don't know why the tests are failing
```
"component":"unset","file":"prow/cmd/peribolos/main.go:202","func":"main.main","level":"fatal",
"msg":"Configuration failed: failed to configure knative-sandbox teams: failed to update UX Writers members: failed to
 list 0(UX Writers) members: return code not 2XX: 404 Not Found","severity":"fatal","time":"2021-02-18T22:56:48Z"}

```

**Comment by evankanderson** [comment]
It looks like there's a bug in the test when you try to add a team with members in one go.

I'll be filling a bug upstream, but if you want to make this an empty team and follow up with a PR adding the team members, those should work as is.

**Comment by rhuss** [comment]
I added the team manually (hope this is ok), so this should be no issue.

/retest

**Comment by csantanapr** [comment]
thank you @rhuss for creating the team manually

**Pull request closed without merging**
