### PR TITLE
Move docs contrib to help section

### PR DESCRIPTION
**Pull request by RichieEscarez**
Update docs contributor content:
- remove all docs files
- ~point to the new "Knative docs" help section~

OTHER DEPENDENT PRS:
This is the knative/community PR, and is 1 of 3:
  - https://github.com/knative/docs/pull/3437
  - https://github.com/knative/website/pull/288

https://github.com/knative/docs/issues/2960

### CODE REVIEW

**Comment by RichieEscarez** [comment]
PREVIEW: https://606e66140a771100079874e5--knative.netlify.app/help/

**Comment by evankanderson** [comment]
I _really_ want this stuff to live in the docs repo...

**Comment by abrennan89** [comment]
> I really want this stuff to live in the docs repo...

+1, idk why it doesn't?

**Comment by omerbensaadon** [comment]
+1

**Comment by RichieEscarez** [comment]
That page exists only to direct people to the new Help content. This is where all docs contributor info has lived since day one so the goal here is to inform and get the user to the new location. You can then completely delete it after some time without negatively impacting the user experience. If nobody is concerned with that we could just silently redirect the pages on the website but those who use GitHub will get a 404.

**Comment by RichieEscarez** [comment]
All docs contributor files have been deleted. This is ready to go now

**Review by evankanderson — COMMENTED** [review]
/lgtm
/approve

Thanks!

If these docs were facing our end-users (developers or cluster administrators), I'd have argued to keep them, but I think our contributor base is well-enough acquainted that they should be able to find the information in the `knative/docs` repo.

Thanks for doing this!

**Pull request merged**
