### PR TITLE
create trademark group

### PR DESCRIPTION
**Pull request by duglin**
Signed-off-by: Doug Davis <dug@us.ibm.com>

### CODE REVIEW

**Comment by mattmoor** [comment]
/assign @knative/steering-committee @knative/technical-oversight-committee 

This LGTM, will ask for a couple more eyeballs

**Comment by bsnchan** [comment]
/lgtm

I'll let someone else approve since I am on the trademark committee :)

**Comment by mattmoor** [comment]
Well, I can't 😅

**Comment by mattmoor** [comment]
oh, I can!

**Pull request merged**
