### PR TITLE
Adjust release leads to the schedule for the upcoming 1.12 release 

### PR DESCRIPTION
**Pull request by ReToCode**
# Changes
- Adjust release leads to the schedule for the upcoming 1.12 release (https://github.com/knative/release/blob/main/README.md#release-schedule)

/assign @skonto

### CODE REVIEW

**Comment by skonto** [comment]
I think you only need to add `Cali0707`, `creydr` is already there. I am trying to avoid another PR and another update for community files.

**Comment by ReToCode** [comment]
@skonto Done. I also removed Vishal-Chdhry as he is not in the release rooster or in this release as a lead.

**Pull request merged**
