### PR TITLE
Add almost complete election documentation for 2020 SC

### LINKED ISSUE #311: Request approval of SC Election details
As much as possible, the EC is trying to base the elections on the TOC elections of April. However, there are some details we don't know, so I'd like to ask the current SC to approve our choices.

## Timeline:
(assumes that Transition Plan is revised in the next couple days)
- Oct 27: call for nominations and exceptions
- Nov 9: call for nominations closes
- Nov 12: voting begins
- Nov 22: last call for exceptions, ballot replacements
- Nov 29: Voting ends
- Dec 3: announce results

## Voter List
- Oct 15 2019 to Oct 15 2020: relevant period for contributions
- Please check https://knative.teststats.cncf.io/d/68/repository-groups?orgId=1 to see which repositories are not represented that are now part of Knative.  Archived repositories are not an issue.

## Nomination Process
- candidates self-nominate
- candidates nominate by opening a PR against community/elections with their profile, and announce that on knative-dev and/or -users
- candidates need at least one +1 (or lgtm) on that profile to merge, as an endorsement

## Voting Details
- options for CIVS: no opinion allowed, no write-ins, detailed but anonymous ballot reporting
- EC will report full ballot results to the SC privately
- EC will report only winners of election publicly

## General
- we will use Google Forms for exception and ballot replacement forms
- all election dates & reminders will be announced to both knative-dev and knative-users
- election deadlines will go on knative community calendar

Please approve, thanks!

@thisisnotapril @geekygirldawn
@pmorie @bsnchan @mbehrendt @anicolao @ronavn

### PR DESCRIPTION
**Pull request by jberkus**
Hey, this is the first PR to set up this repo for the steering committee elections.  There's a LOT of docs here, so I wanted to post it early for you to review.  It includes:

* Creates TOC and SC subfolders of elections.  
* Adds README for 2020 SC election.  
* Adds mechanics/SC.md.  
* Adds candidate template for 2020 SC election.
* Corrects "exemption" to "exception" in all documents.

Still TODO:

* voters.md for SC election
* adding election procedural steps to general elections README

Please review!  

Particularly, the nominations procedure for this election requires saving candidate profiles to the elections/2020/sc/ directory.  This means that *either* someone on the Election Committee will need permissions to merge PRs to that directory, or an existing committer will need to be available to do it.

Fixes #311 

Review:
@thisisnotapril @geekygirldawn @macruzbar-zz
@pmorie @bsnchan @mbehrendt @anicolao @ronavn

### CODE REVIEW

**Comment by bsnchan** [comment]
Thanks for this @jberkus ! I believe we can open up a PR so that peribolos can give the election officers OWNERS access to the `/2020/sc` directory if that's the approach you'd like to use. If not, I'm happy to help with PR merging

/lgtm

**Comment by jberkus** [comment]
@bsnchan if you're under peribolos, then yes.  I'll add an OWNERs file to the election folder in my branch.

**Comment by jberkus** [comment]
Rolled back OWNERs change, because apparently all three of us need to join the org first.

**Comment by jberkus** [comment]
@googlebot I signed it!

**Review by thisisnotapril — APPROVED** [review]

**Comment by jberkus** [comment]
Now, with voters.md, which gives us compete election information.

**Pull request merged**
