### PR TITLE
Drop mattmoor from TOC groups

### PR DESCRIPTION
**Pull request by mattmoor**
cc @knative/technical-oversight-committee @knative/steering-committee

### CODE REVIEW

**Comment by vagababov** [comment]
😢

**Comment by thisisnotapril** [comment]
Thank you Matt for all your hard work and leadership on the project! And thank you for leading by example on the importance of navigating burn out. Enjoy your break!

**Comment by evankanderson** [comment]
Noo.... thank you Matt, and have a good break.

/lgtm

**Pull request merged**
