### PR TITLE
Add links to new content templates

### PR DESCRIPTION
**Pull request by RichieEscarez**
Replace doc template with the version that was copied in knative/docs. See https://github.com/knative/docs/pull/3341/ for the dependent updates (new blog template/instructions).

### CODE REVIEW

**Review by abrennan89 — APPROVED** [review]
Awesome, thanks @RichieEscarez ! :tada: 
/lgtm

**Comment by RichieEscarez** [comment]
@evankanderson we need approval please.

**Review by evankanderson — COMMENTED** [review]
Wondering if we can move this directory completely over to `knative/docs` pretty soon, since there is only a file or two left in here.

/lgtm
/approve

(I think Richie can still approve, but he would have needed to type `/approve`). He might still need to, because I'm not sure I have OWNERS.)

**Comment by evankanderson** [comment]
Yep, this needs Richie to type `/approve` (or Sam), based on https://github.com/knative/community/blob/main/OWNERS_ALIASES

**Comment by RichieEscarez** [comment]
I thought Prow blocked us from LGTMing and Approving our own PRs?

**Comment by RichieEscarez** [comment]
I guess not? Thanks @evankanderson !

**Comment by RichieEscarez** [comment]
> Wondering if we can move this directory completely over to `knative/docs` pretty soon, since there is only a file or two left in here.

Through https://github.com/knative/docs/issues/2960, all that will remain would be links to the new /authoring/ docs. (We don't have a way to redirect GitHub repo links, do we?)

**Comment by evankanderson** [comment]
> I thought Prow blocked us from LGTMing and Approving our own PRs?

Prow requires that _someone_ in OWNERS has done an `/approve`. Until a few weeks ago, we were operating with a plugin that said "authors implicitly `/approve` their own PRs". We removed that, but you can still explicitly `/approve` a PR.

Prow _also_ requires that someone who is not the author has done an `/lgtm` on the PR. That person does not need to be in OWNERS.

**Comment by evankanderson** [comment]
> > Wondering if we can move this directory completely over to `knative/docs` pretty soon, since there is only a file or two left in here.
> 
> Through [knative/docs#2960](https://github.com/knative/docs/issues/2960), all that will remain would be links to the new /authoring/ docs. (We don't have a way to redirect GitHub repo links, do we?)

I'm not sure which repo links you're thinking of, but it seems reasonable to remove the directory and put the docs about "how to work with docs" next to the docs, in the same way that serving or eventing has docs about "how to write code for $COMPONENT" next to the component.

TBH, except for this being surfaced on the website, I'd be surprised if anyone was able to find the docs here.

I think this directory is an artifact of the fact that all the community governance docs used to live in `docs` when the project launched, and then we created the `community` repo later.

**Comment by evankanderson** [comment]
(And then everything from the `community` directory got moved over here at once when the split was done.)

**Pull request merged**
