### PR TITLE
Chainguard taking ownership of eventing-rabbitmq

### PR DESCRIPTION
**Pull request by dprotaso**
As a results of some restructuring due to the VMware/Broadcom acquisition we're unable to maintain this integration.

I've chatted with Chainguard and they use this integration in production so I'm transitioning approver responsibilities to them.

If anyone else would also like approver status I'd imagine the help would be welcome.

### CODE REVIEW

**Comment by dprotaso** [comment]
/assign @tcnghia 

/hold there's been some changes in `knative/eventing` that broke the integration (https://github.com/knative-extensions/eventing-rabbitmq/pull/1310)

Will unhold when that's fixed.

**Comment by dprotaso** [comment]
cc @gabo1208

**Comment by gabo1208** [comment]
I could be left as an approver if that's ok

**Review by gabo1208 — APPROVED** [review]

**Pull request merged**
