### PR TITLE
Add myself as TOC candidate

### PR DESCRIPTION
**Pull request by kvmware**
Thanks for taking a look! :eyes:

### CODE REVIEW

**Comment by dprotaso** [comment]
💯

**Comment by izabelacg** [comment]
💯

**Comment by evankanderson** [comment]
While some of our previous TOC members have had opinions about our automation, I don't think we've had a productivity WG lead as a TOC member.  As productivity WG ends up having to install Knative dozens of times daily, I support @kvmware as a TOC candidate.

**Comment by kauana** [comment]
💯

**Comment by jsanin-vmw** [comment]
Go @kvmware !
For the reasons you described, I think you'd do a great job!

**Comment by cardil** [comment]
I think @kvmware will be a great TOC member!

**Comment by lance** [comment]
👍 for @kvmware

**Comment by kvmware** [comment]
Thank you all for your support :heart: Please remember to actually vote https://elections.knative.dev/app/elections/2023-TOC :pray:

**Pull request merged**
