### PR TITLE
Update Steering Committee with the newly elected members

### PR DESCRIPTION
**Pull request by vaikas**
Congratulations @csantanapr and @lance!!!

Also move @mbehrendt to Emeritus Committee Members, thank you for your
service!!!

Signed-off-by: Ville Aikas <vaikas@chainguard.dev>

# Changes

- Add @csantanapr @lance to Steering Committee as per election results.
- Move @mbehrendt to Emeritus Committee Members
-

/kind <kind>

Fixes #

**Release Note**

```release-note

```

**Docs**

```docs

```

### CODE REVIEW

**Comment by csantanapr** [comment]
@vaikas you want to update peribolos also in this PR?
This way all things to update to add a member is capture in one PR for the future

**Comment by vaikas** [comment]
Sure thing, done

**Comment by csantanapr** [comment]
Thank you compadre!

**Comment by csantanapr** [comment]
/lgtm
🙏

**Pull request merged**
