### PR TITLE
Add skonto as reviewer for Serving API & Autoscaling

### PR DESCRIPTION
**Pull request by skonto**
/cc @julz @nak3

### CODE REVIEW

**Comment by nak3** [comment]
/assign @julz @dprotaso 

LGTM. It seem requirement of the reviewer is not documented in https://github.com/knative/community/blob/main/ROLES.md :thinking:

**Review by julz — APPROVED** [review]
/lgtm
/approve

**Comment by dprotaso** [comment]
> LGTM. It seem requirement of the reviewer is not documented in https://github.com/knative/community/blob/main/ROLES.md 🤔

Honestly it's anyone who wants to start getting notified and wants to help with reviews ;)

**Pull request merged**
