### PR TITLE
Update repo guidelines with CLOMonitor instructions

### PR DESCRIPTION
**Pull request by aliok**
# Changes

- :gift: Update some docs and Github issue template with CLOMonitor instructions

Context:
- I recently added Knative missing _core_ repos to the project [dashboard](https://clomonitor.io/projects/cncf/knative) and [CLOTributor](https://clotributor.dev/search?project=knative&page=1)
- I added the sandbox repos to CLOTributor only (in progress: https://github.com/cncf/clomonitor/pull/1076)
- I thought I should write how to do these in the docs

/kind <kind>

Fixes #

**Release Note**

```release-note

```

**Docs**

```docs

```

### CODE REVIEW

**Comment by aliok** [comment]
cc @knative/technical-oversight-committee

**Comment by kvmware** [comment]
lgtm

**Review by psschwei — COMMENTED** [review]
/lgtm

@knative/steering-committee needs to give final approval

**Review by lance — COMMENTED** [review]
/lgtm
/unhold

**Pull request merged**
