### PR TITLE
Update our min K8s version principle to exclude releases in maintenance mode

### PR DESCRIPTION
**Pull request by dprotaso**
Fixes: https://github.com/knative/community/issues/827

### CODE REVIEW

**Comment by evankanderson** [comment]
Policy reference: https://kubernetes.io/releases/patch-releases/#support-period

The rationale is presumedly to reduce the size of our testing matrix, and we don't expect that these releases will change much?

Or is the rationale to get access to new Kubernetes features 2 months earlier?

**Comment by dprotaso** [comment]
I view the maintenance window as an extra two month buffer to transition to a K8s version in the 'standard support period'. 

We should have an available Knative release that supports that 'newer' version.  We generally 'support' newer K8s version but we don't stress them the same way we do our target min version - ie. running prow scale tests etc.

**Comment by dprotaso** [comment]
@rhuss posted https://github.com/knative/community/issues/827#issuecomment-970041524

> > [dave] Our min K8s policy states we support whatever is supported upstream at the time of a Knative release. We should update the language to exclude the 'maintenance mode'
> 
> Would it make sense to also include such a notion of a 'maintenance mode'? I mean, when a k8s enters maintenance mode it will be still 2 months around, which is for one future Knative version, too. I don't mind being more restrictive than k8s and that is probably the right thing to do.
> 
> So +1 from my side but would love to hear some more opinions before merging it.

**Comment by evankanderson** [comment]
/approve

Discussed this in the TOC meeting at Nov 18; we might also want to say "we (the community) will _test_" (rather than "support").

**Comment by dprotaso** [comment]
> we might also want to say "we (the community) will _test_" (rather than "support").

'support' is qualified later in the paragraph

>  Only the latest patch release of the minor version is tested for support. Support for versions prior to that are best effort, or by vendors.

**Comment by markusthoemmes** [comment]
LGTM

**Pull request merged**
