### PR TITLE
Add creydr as eventing approver

### PR DESCRIPTION
**Pull request by creydr**
Adding myself as an eventing approver.

From [ROLES.md](https://github.com/knative/community/blob/main/ROLES.md#approver):

**Requirements**
* Reviewer of other people's contributions for about 3 months :heavy_check_mark: 
* Should have reviewed or contributed to non-trivial PRs: https://github.com/knative/eventing/pulls?q=is%3Apr+author%3Acreydr+-label%3Asize%2FS+-label%3Asize%2FXS+-label%3Asize%2FM+is%3Aclosed+
* Nominated by a Working Group Lead with no objections from other leads: CC @pierDipi as eventing WG lead

/cc @pierDipi

### CODE REVIEW

**Review by pierDipi — APPROVED** [review]
Thanks for all the contributions!

/lgtm
/approve

**Comment by kvmware** [comment]
Congrats!

**Review by psschwei — COMMENTED** [review]
:partying_face: 

/approve
/hold
(just in case others want to comment)

**Pull request merged**
