### PR TITLE
add term column

### PR DESCRIPTION
**Pull request by vaikas**
# Changes

- As discussed in the steering meeting on 2021-02-25 it was deemed that having a new column indicating when a member of TOC / SC got their seat would be a good thing. So, add that.
-
-

/kind <kind>

Fixes #

**Release Note**

```release-note

```

**Docs**

```docs

```

### CODE REVIEW

**Review by evankanderson — COMMENTED** [review]
/lgtm
/approve

**Comment by thisisnotapril** [comment]
lgtm, thank you @vaikas!

**Pull request merged**
