### PR TITLE
Migrate the Feature Tracks proposal into the community repo.

### PR DESCRIPTION
**Pull request by mattmoor**
OG: https://docs.google.com/document/d/1QRREfL8gSVSURHMkDLjDtMh1BBsNiwfmaBiGnJUDQ2g/edit#

/hold
/assign @vaikas-google @evankanderson

### CODE REVIEW

**Comment by evankanderson** [comment]
Can we move the new document to the "mechanics" sub-directory?

I'd like to eventually set OWNERS in mechanics to TOC, so that the governance docs are at the top-level with restricted OWNERS, and then the more dynamic engineering docs don't require Steering Committee approval.

**Comment by mattmoor** [comment]
I moved things under `mechanics/`

**Pull request merged**
