### PR TITLE
Remove SAP from ADOPTERS

### PR DESCRIPTION
**Pull request by travis-minke-sap**
# Changes

- :broom: Remove SAP from ADOPTERS.md as the Event-Mesh project is no longer based on Knative Eventing.

/kind cleanup

Fixes #

**Release Note**

```release-note

```

**Docs**

```docs

```

### CODE REVIEW

**Comment by lance** [comment]
@travis-minke-sap thanks for the update. Any chance you can sign the CLA for this change?

**Comment by travis-minke-sap** [comment]
> @travis-minke-sap thanks for the update. Any chance you can sign the CLA for this change?

Well... I started down that path and discovered that SAP is not listed as a contributing organization.  We left prior to the CNCF or Licensing CLA changes.  I can't justify trying to setup SAP as a contributing org just to remove us ; ).  It's a one-line PR - is there anyway you or someone else could make a matching PR to push through?  Thanks - sorry - etc. ; )

**Comment by lance** [comment]
> > @travis-minke-sap thanks for the update. Any chance you can sign the CLA for this change?
> 
> Well... I started down that path and discovered that SAP is not listed as a contributing organization. We left prior to the CNCF or Licensing CLA changes. I can't justify trying to setup SAP as a contributing org just to remove us ; ). It's a one-line PR - is there anyway you or someone else could make a matching PR to push through? Thanks - sorry - etc. ; )

Totally understand. I think probably we'll just need to open a duplicate PR by someone who has already signed it. Let's see what others say.

/cc @knative/steering-committee @knative/technical-oversight-committee

**Comment by travis-minke-sap** [comment]
/close

Haven't signed latest CLA so duplicate was created - see https://github.com/knative/community/pull/1147

**Pull request closed without merging**
