### PR TITLE
added astelmashenko as Knative Sandbox member

### PR DESCRIPTION
**Pull request by astelmashenko**
added myself as sandbox member:
- I'm active in [user group](https://groups.google.com/g/knative-users/)  (Andrey Stelmashenko, astelmashenko@viax.io, using corporate account there)
- requested subscription in [dev group](https://groups.google.com/g/knative-dev?pli=1)
- made a PR regarding [tracing propagation](https://github.com/knative-sandbox/eventing-natss/pull/342) and going to do more, because k8s native technologies are interesting to me (I promoted knative in a company where I work)

### CODE REVIEW

**Comment by zroubalik** [comment]
@astelmashenko do you want to add yourself to peribolos/knative.yaml as well?

**Comment by astelmashenko** [comment]
@zroubalik , yes I do. Added to knative.yaml as well.

**Comment by astelmashenko** [comment]
@zroubalik , is anything else needed? is it ok to merge?

**Pull request merged**
