### PR TITLE
Add pmbanugo to the Doc group

### PR DESCRIPTION
**Pull request by pmbanugo**
Add pmbanugo as a member of the community, specifically the Doc group

# Changes

- :gift: Add pmbanugo as a member of the Doc group

/kind documentation

### CODE REVIEW

**Comment by pmbanugo** [comment]
@googlebot I signed it!

**Review by evankanderson — COMMENTED** [review]
Awesome that you signed up for reviewing docs changes as well!

It's not necessary to be in any of the groups at the bottom, but I'm excited to see more "docs review" volunteers.

/lgtm
/approve

**Pull request merged**
