### PR TITLE
TM committee dissolving

### LINKED ISSUE #1399: PROCESS CHANGE: Dissolving TradeMark Commitee
As we are part of CNCF we no longer need Trademark Committee. 
Current charter for Trademark commitee is  as following:

```
1. Advise the Trademark owner on the definition and enforcement of the "Knative" trademark usage and branding guidelines.
2. Review and approve conformance rules and tests that define brand use decisions.
3. Review and approve the scope and definition of additional derivative Knative marks (e.g. Knative Serving, Knative Core, etc).

Only the Trademark Committee can redefine its own charter, membership, and authority over Knative Trademark, conformance, and brand decisions.
```

At SC and TOC we believe that Conformance should and can be handled by TOC and point 1 and 3 are no longer needed. 
Since only TM can redefine its own charter, membership and authority.
Please let us know your thoughts and wishes. 

P.S: No meeting has happened since Feb 2023 due to no quorum.

### PR DESCRIPTION
**Pull request by aliok**
Fixes #1399

# Changes

- Dissolve TM committee
- As written in https://github.com/knative/community/issues/1399:
  - Move "Define brand use decisions." to SC
  - Move "Review and approve conformance rules and tests" to TOC
- The SC's new responsibility is written according to CNCF project template: https://github.com/cncf/project-template/blob/54a33f5aba96bb668dc1cd578e836da7ec4b8b73/GOVERNANCE-elections.md#charter
- TOC's new responsibility is to **advise** SC about conformance tests and scope.
- Blog post PR: https://github.com/knative/docs/pull/5852
- NOTE: after this change, we should send an email to Knative mailing lists

/kind <kind>

Fixes #

**Release Note**

```release-note

```

**Docs**

```docs

```

### CODE REVIEW

**Comment by krsna-m** [comment]
Thanks for putting this together

**Comment by psschwei** [comment]
+1

**Comment by dprotaso** [comment]
+1

**Comment by salaboy** [comment]
+1

**Comment by puerco** [comment]
+1

**Comment by evankanderson** [comment]
It looks like we have quorum here, adding an

/lgtm

**Comment by evankanderson** [comment]
Adding, here is the recording of the meeting where the TM voted to dissolve the separated governance structure: https://zoom.us/rec/share/SQdqoQVUlYjE4Q4KYSOgPzfq2aP5Hs1A0F6SN-zm8SynkOhnp6h_3KpXTyrEJuhH.uSIcatWGYOwNnFk4

**Comment by aliok** [comment]
- Blogpost published: https://knative.dev/blog/steering/2024-02-14-trademark-committee-dissolved/
- Knative users announcement: https://groups.google.com/g/knative-users/c/kezrm7QckfA
- Knative dev announcement: https://groups.google.com/g/knative-dev/c/UgcGwDkJhSY

**Pull request merged**
