### PR TITLE
Add firatbezir as Knative eventing writer

### PR DESCRIPTION
**Pull request by firatbezir**
Hi Knative team,

I am Firat Bezir, a mentee for the LFX Mentorship program working on the Knative Eventing Onboarding Improvement project. As part of my mentorship, I need to create and manage a project under the Knative organization.

Please add me as a member of the Knative organization to facilitate this process. By becoming a member, I will no longer need to use the ok-to-test labels to run tests, which will streamline my contributions and help me be more efficient in my work.

Changes:
- Add @firatbezir  as a member of the Knative organization and Knative-sandbox.

**Release Note**
```release-note
N/A

### CODE REVIEW

**Comment by dsimansk** [comment]
@pierDipi @Cali0707 @Leo6Leo can any of you ACK it's our new mentee pls? :)

**Comment by Leo6Leo** [comment]
/unhold Thanks @dsimansk 
And welcome! @firatbezir

**Pull request merged**
