### PR TITLE
Add knative-automation to knative and knative-sandbox

### PR DESCRIPTION
**Pull request by nak3**
As per title, adding @knative-automation to knative and knative-sandbox community.

Currently we need to add `/ok-to-test` every auto PR like https://github.com/knative/serving/pull/9943.

/cc @knative/technical-oversight-committee

### CODE REVIEW

**Comment by mattmoor** [comment]
I sort of like the least privilege aspect of the status quo, but (like you) am also annoyed by it.  I'd love to hear the thoughts of others here.

/assign @knative/technical-oversight-committee

**Comment by tcnghia** [comment]
I think if we put a lot of comments to explain the special casing here we're probably good.

**Review by mattmoor — APPROVED** [review]
/lgtm

Discussed at TOC, and folks seem ok with the change.  Will need to log in to accept the invitation once this lands for it to take effect.

**Comment by nak3** [comment]
Umm... the PR still needs `/ok-to-test`.  @mattmoor @tcnghia Do you have any idea the reason?

https://github.com/knative/serving/pull/9993
https://github.com/knative/serving/pull/9992

**Comment by mattmoor** [comment]
Yeah, we need to figure out what the other bots are doing for 2FA :-/

**Comment by mattmoor** [comment]
The "solution" in slack is to use a personal phone, so I used mine.  This is now configured.

**Pull request merged**
