### PR TITLE
Updated links for Working-GROUPS.md

### PR DESCRIPTION
**Pull request by macruzbar**
I updated the links to the md file describing working groups

### CODE REVIEW

**Comment by mpetason** [comment]
I think this breaks the links. Are these files getting moved under the community/working-groups/ folder? The current version has WORKING-GROUPS.md top level.

**Comment by mpetason** [comment]
Ah I see, it's getting moved but that was a while ago.

**Comment by evankanderson** [comment]
/lgtm
/approve

@macruzbar you need to get yourself added to the [Google](https://github.com/Google) org, which should get the CLA signed for you automatically.

**Comment by evankanderson** [comment]
I think #123 covers this across a few more locations in the repo

**Pull request closed without merging**
