### PR TITLE
add kn-plugin-quickstart approvers github team

### PR DESCRIPTION
**Pull request by csantanapr**
Add kn-plugin-quickstart approve group for peribolos

### CODE REVIEW

**Comment by csantanapr** [comment]
pull-knative-sandbox-peribolos failed
Error
```
{"component":"unset","file":"prow/cmd/peribolos/main.go:202","func":"main.main","level":"fatal","msg":"Configuration failed: failed to configure knative-sandbox teams: failed to update kn-plugin-quickstart Approvers members: failed to list 0(kn-plugin-quickstart Approvers) members: return code not 2XX: 404 Not Found","severity":"fatal","time":"2021-07-19T16:01:21Z"}
```
Do we need to create the github team manually first?

**Review by rhuss — COMMENTED** [review]
Looks good but you need to reference this team also in the repo definition. See the other plugin projects as blueprints.

**Comment by rhuss** [comment]
sorry my bad, the reference goes from team -> repo. Also, I created the team manually, so we should be good.

/lgtm
/approve

**Comment by csantanapr** [comment]
I have the PR here @rhuss, is this the change you are referring or something else?
https://github.com/knative-sandbox/kn-plugin-quickstart/pull/47

**Comment by csantanapr** [comment]
@rhuss thanks for creating team manually 👍

**Pull request merged**
