### PR TITLE
Update leads for Productivity WG

### PR DESCRIPTION
**Pull request by adrcunha**
Adriano is leaving Knative.

### CODE REVIEW

**Comment by rhuss** [comment]
@adrcunha Thanks a lot for your very responsive support, really appreciated! Don't know how we could have moved forward on the Knative client E2E test without you. 🙏

All the best for your new challenges !

**Comment by bsnchan** [comment]
Thanks for updating us and thank you for all you've done on Knative! Best of luck on whatever is next for you!

**Pull request merged**
