### PR TITLE
Add peribolos schema validation workflow

### PR DESCRIPTION
**Pull request by kvmware**
This will catch errors that our current presubmit job doesn't without blowing up when adding a team. Additionally, this is a 10s run process vs the current 3min job.

### CODE REVIEW

**Comment by kvmware** [comment]
@dprotaso

**Comment by kvmware** [comment]
Fixes: https://github.com/knative/test-infra/issues/3384

**Review by dprotaso — APPROVED** [review]
/lgtm
/approve
/hold'ing for the nit

FYI: I'm a bit mixed on using python - it requires new contributors to learn python in addition to go. But this change seems simple enough.

**Comment by dprotaso** [comment]
lol whoops

I guess you can't type `/hold'ing`

**Pull request merged**
