### PR TITLE
Add Leo Li as release lead for 1.13

### PR DESCRIPTION
**Pull request by skonto**
# Changes

- See discussion [here](https://cloud-native.slack.com/archives/C04LY4Y3EHF/p1704466731952259?thread_ts=1704451381.388299&cid=C04LY4Y3EHF).

### CODE REVIEW

**Review by pierDipi — APPROVED** [review]
/lgtm

**Review by ReToCode — APPROVED** [review]
/lgtm
/approve

**Comment by ReToCode** [comment]
@knative/technical-oversight-committee PTAL.

**Pull request merged**
