### PR TITLE
Add permissions for Knative Release Leads

### PR DESCRIPTION
**Pull request by tcnghia**
I am not sure what permissions are needed, so start with admin.

### CODE REVIEW

**Comment by mattmoor** [comment]
/assign @Harwayne @yanweiguo 
/lgtm
/hold

This LGTM, but I'd like Adam and Yanwei to acknowledge that they are about to gain temporary superpowers first 😅

**Comment by tcnghia** [comment]
@Harwayne are you ok with having super power? Forget about that uncle Ben...

**Comment by tcnghia** [comment]
/unhold
@Harwayne is aware of this and already working with @yanweiguo to release eventing this release.

**Pull request merged**
