### PR TITLE
Working at VMware and will contribute to Knative

### PR DESCRIPTION
**Pull request by pradnyad23**
# Changes
 Add myself to the list of community members in knative.yaml and knative-sandbox.yaml.

- :gift: Add new feature
- :bug: Fix bug
- :broom: Update or clean up current behavior
- :wastebasket: Remove feature or internal logic
-->

-
-
-

/kind <kind>

Fixes #

**Release Note**

```release-note

```

**Docs**

```docs

```

### CODE REVIEW

**Comment by csantanapr** [comment]
There is no need to be a member of the github org to contribute to Knative, you can fork the git repos and submit PRs.

@dprotaso The person claims to be working for VMware, could you review this PR?

/hold
/assign @dprotaso

**Comment by dprotaso** [comment]
> There is no need to be a member of the github org to contribute to Knative, you can fork the git repos and submit PRs.

Being a member is necessary for Prow to add folks as reviewers to PRs

**Comment by dprotaso** [comment]
@pradnyad23 you'll want to setup EasyCLA - instructions are in this comment

https://github.com/knative/community/pull/1263#issuecomment-1416424638

**Pull request closed without merging**
