### PR TITLE
Add Navid as a Client WG Technical Lead

### PR DESCRIPTION
**Pull request by rhuss**
Hereby I nominate Navid Shaikh as a Technical Working Group Lead for the Knatice Client Working Group

He mets all the [WG lead criteria](https://knative.dev/community/contributing/roles/#working-group-technical-lead) and is also the [top contributor of knative/client](https://github.com/knative/client/graphs/contributors):

* Approver for a relevant part of the codebase for at least 3 months  --> **yes** (14 months)
  - Added as approver with https://github.com/knative/client/pull/321
* Member for at least 6 months --> **yes**
* Primary reviewer for 20 substantial PRs. --> **ca. 22 PRs**
  - https://github.com/knative/client/pulls?q=is%3Apr+is%3Aclosed+assignee%3Anavidshaikh+label%3Asize%2FXXL+
  - https://github.com/knative/client/pulls?q=is%3Apr+is%3Aclosed+assignee%3Anavidshaikh+label%3Asize%2FXL+
* Reviewed or merged at least 50 PRs. --> **ca. 169 PRs**
  - https://github.com/knative/client/pulls?q=is%3Apr+is%3Aclosed+assignee%3Anavidshaikh

cc: @knative/technical-oversight-committee

### CODE REVIEW

**Comment by matzew** [comment]
/lgtm :-) 

:tada:

**Comment by evankanderson** [comment]
Two other items:

1. Updating the Peribolos configs in this repo under `peribolos/knative*.yaml`
2. Updating OWNERS in the appropriate repos.

**Comment by evankanderson** [comment]
@sixolet FYI

If this is a surprise/problem, object in the next week or so.

**Pull request merged**
