### PR TITLE
Update knative-extensions.yaml

### PR DESCRIPTION
**Pull request by tzununbekov**
In response to the received request - remove `tzununbekov` from the "approvers" role.

# Changes

-
-
-

/kind <kind>

Fixes #

**Release Note**

```release-note

```

**Docs**

```docs

```

### CODE REVIEW

**Review by matzew — APPROVED** [review]
/lgtm
(but it does not :cry: )

/approve

**Comment by aliok** [comment]
Can you run the ./hack/update-codegen.sh

**Comment by aliok** [comment]
Thanks Timur and you're welcome back anytime

**Pull request merged**
