### PR TITLE
Add April to OWNERS_ALIASES

### PR DESCRIPTION
**Pull request by evankanderson**
Since she's on the Steering Committee. In the spirit of #269 ; I'll resolve the merge conflict.

/hold

### CODE REVIEW

**Comment by evankanderson** [comment]
/hold cancel
/assign @ronavn 

Ron, you'll need to `/approve` this to allow it to submit, since Steering has OWNERS on all the governance documents.

**Review by ronavn — APPROVED** [review]

**Comment by ronavn** [comment]
lgtm

**Pull request merged**
