### PR TITLE
Zbynek stepping down from TOC

### PR DESCRIPTION
**Pull request by zroubalik**
# Changes

- Zbynek moved off TOC

### CODE REVIEW

**Review by zroubalik — COMMENTED** [review]
/hold

I will need to hand over admin rights to this repo:
https://github.com/knative-sandbox/eventing-autoscaler-keda

https://github.com/knative/community/blob/06851c4dc6983ff2e005ed43c180cfacc75e708d/peribolos/knative-sandbox-OWNERS_ALIASES#L21C1-L22


https://github.com/knative/community/blob/06851c4dc6983ff2e005ed43c180cfacc75e708d/peribolos/knative-sandbox.yaml#L857

**Comment by dsimansk** [comment]
@zroubalik ready to let go?

**Comment by rhuss** [comment]
@zroubalik not so easy to get rid of us :-P (just kidding ...)

**Comment by zroubalik** [comment]
> @zroubalik not so easy to get rid of us :-P (just kidding ...)

🤷‍♂️ 😄

**Comment by lance** [comment]
/lgtm

Good luck in your new adventures, @zroubalik!

**Comment by dprotaso** [comment]
@knative/steering-committee needs to approve this

**Pull request merged**
