### PR TITLE
Remove skonto, not in org

### PR DESCRIPTION
**Pull request by kvmware**
Unblocks https://github.com/knative-sandbox/knobots/pull/163

```
- skonto
-- User is not a member of the org. User is not a collaborator. Satisfy at least one of these conditions to make the user trusted.
```

### CODE REVIEW

**Comment by dprotaso** [comment]
@skonto accepted the invite - we shouldn't need to remove him

**Comment by skonto** [comment]
What needs to be done here? I have accepted the knative-sandbox invitation already.

**Comment by dprotaso** [comment]
Running`/verify-owners` on blocked PRs works to remove the bad label

**Pull request closed without merging**
