### PR TITLE
adding myself to trademark committee

### PR DESCRIPTION
**Pull request by spencerdillard**
# Changes

-
-
-

/kind <kind>

Fixes #

**Release Note**

```release-note

```

**Docs**

```docs

```

### CODE REVIEW

**Comment by bsnchan** [comment]
@spencerdillard do you want to remove Ron from the TM committee so it clearly shows you're replacing him?

**Comment by spencerdillard** [comment]
Updated change with a commit to remove ronavn

**Comment by evankanderson** [comment]
Unfortunately, there's a comment at the top of this file that indicates there's a different source-of-truth, and this file is derived from that one. #661 updated the source-of-truth file, and once @spencerdillard has accepted the invite to the GitHub org, this PR or #663 should update the file-level access control.

Sorry it's a bit more of a mess than Google3 equivalent!

**Comment by evankanderson** [comment]
In either case, @spencerdillard will need to find the email from GitHub inviting him to the org or go to https://github.com/orgs/knative/people and accept the invite to the Knative org before these can be merged.

**Comment by spencerdillard** [comment]
I just accepted the Github invite so hopefully that should fix it. It's
strange to be back in Github again (it's been ~10 years) so please holler
if I make any messes!

**Comment by bsnchan** [comment]
Hey @spencerdillard it looks like your invitation is still pending. If you go to https://github.com/knative, you should see an invitation at the top of your page that you'll need to accept.

**Comment by spencerdillard** [comment]
Strange - although i am sure I previously accepted, the invite was on that
page, and I just (re-)accepted it. Sorry about that!

**Comment by bsnchan** [comment]
Looks like that worked! I'm closing this PR in favour of https://github.com/knative/community/pull/663

**Pull request closed without merging**
