### PR TITLE
Add Leo6Leo as eventing approver

### PR DESCRIPTION
**Pull request by Leo6Leo**
# Changes

- Add @Leo6Leo as an eventing approver (follow up on the Eventing WG meeting)

cc @pierDipi
<!--
In addition, categorize the changes you're making using the "/kind" Prow command, example:

### CODE REVIEW

**Review by pierDipi — APPROVED** [review]
Great @Leo6Leo 

/lgtm
/approve

**Comment by Cali0707** [comment]
@dsimansk @pierDipi can we unhold the PR?

**Comment by Cali0707** [comment]
Congrats @Leo6Leo - well deserved!!! :tada:

**Pull request merged**
