### PR TITLE
add lance as candidate for the 2021 SC elections

### PR DESCRIPTION
**Pull request by lance**
I am throwing my hat in the ring for a seat on the Steering Committee. 

In my role as technical architect of the Boson Project - a project that brings a function-focused developer experience to Knative - I have been involved on the periphery of Knative since 2019. In the fall of 2021, the core of Boson Project's work was donated to Knative and now exists as a part of Knative Sandbox. I am the Function Task Force lead for this project, and guide the technical efforts towards achieving Functions as a first class citizen of Knative. To Knative core, I have over 200+ contributions primarily in documentation, samples and infrastructure. Outside of the Knative ecosystem, I have been active in the open source community for over a decade as a regular contributor to Node.js core and other widely used technologies.

I believe that Knative has come a long way in the last two years, to become a solid platform for serverless, event driven applications. While continuing to evolve and improve the core Serving and Eventing components of Kative, I believe now is the time for a new focus on the developer experience. Kative is nothing if developers aren't writing applications that can run on it, and with Functions, I would like to make that as frictionless as possible. I believe developer UX is a crucial component for the Steering Committee's focus over the coming years, and know that I can bring a unique perspective to that effort.

### CODE REVIEW

**Comment by devguyio** [comment]
> I believe developer UX is a crucial component for the Steering Committee's focus over the coming years, and know that I can bring a unique perspective to that effort.

You had me at this @lance ! I believe this is a very refreshing and focused mission for a SC member. 👏🏽 💯 ❤️

**Comment by jberkus** [comment]
Lance meets the requirements to run for SC.

/approve
/lgtm

**Comment by zroubalik** [comment]
+1 Lance!

**Comment by nainaz** [comment]
I wholeheartedly endorse your candidacy Lance. UX experience for Knative through functions is going to be the big focus and you will be a great fit.

**Comment by lkingland** [comment]
You have just the right demeanor for this sort of thing Lance.
+1 indeed

**Comment by aliok** [comment]
I think you would be a great fit Lance.
+1

**Pull request merged**
