### PR TITLE
Add myself to knative community members

### PR DESCRIPTION
**Pull request by kauana**
Add myself to the list of community members in `knative.yaml` and `knative-sandbox.yaml`.

### CODE REVIEW

**Comment by dprotaso** [comment]
I'm sponsoring this membership - @kauana  works on the VMware product packaging Knative and will start contributing upstream via code reviews/prs etc.

**Comment by lance** [comment]
@kauana you need to run `./hack/update-codegen.sh`

**Comment by kvmware** [comment]
Hmm shouldn't our CI checks throw some issue about update-codegen not being ran?
There seems to be an issue as well with codegen/gen-alias tool because @kauana told me she did run it and I also tried running it with her username as well and even tried removing other members and there was no change in the OWNER files... @kauana maybe open an issue and we can investigate it.

**Comment by kauana** [comment]
Thanks @kvmware, I just created an issue [here](https://github.com/knative/community/issues/1238).

**Review by psschwei — COMMENTED** [review]
/approve

**Pull request merged**
