### PR TITLE
Add charters for all WGs that have them.

### LINKED ISSUE #410: Backfill charters for all working groups
It's unclear from [WORKING-GROUPS.md](https://github.com/knative/community/blob/master/working-groups/WORKING-GROUPS.md) what is the scope of existing working groups and the problems they are trying to solve.

We should have our WGs backfill/refine their charters.

### PR DESCRIPTION
**Pull request by evankanderson**
Fixes #410.

For all WGs except Event Delivery, I did the following:

1. Search in team drive for the team's charter doc. Other terms include: "proposal" and "mission"
2. Use the ["Docs to Markdown"](https://workspace.google.com/marketplace/app/docs_to_markdown/700168918607) plugin to convert to markdown.
3. Run `prettier --write CHARTER.md` on the output from 2
4. Clean up the header and check sections quickly.

I did a little more cleanup on Event Delivery, but it's still largely the "channels wg" charter.

### CODE REVIEW

**Comment by evankanderson** [comment]
Review here:

https://github.com/knative/community/tree/5ee5e95d6693090d2196eb91844836899c013df2/working-groups/WORKING-GROUPS.md

Note that Serving API, Networking, and Autoscaling do not have existing charters.

/assign @dprotaso @rhuss

**Comment by evankanderson** [comment]
Ref: rename of Channels to Event Delivery: https://docs.google.com/document/d/14exo2bqyvYIO_9A4AZ7eGfWXSxqb1mhTaq24G63t67c/edit

**Comment by rhuss** [comment]
Thanks, this is very helpful. I would merge those, even when out-dated and maybe the formatting is not perfect and then open issues in the respective repositories to update their charted document in the community repository.

**Review by dprotaso — APPROVED** [review]

**Review by rhuss — APPROVED** [review]

**Pull request merged**
