### PR TITLE
include 0.24 release in release version table

### PR DESCRIPTION
**Pull request by dprotaso**
rendered: https://github.com/knative/community/blob/94126f10bafc99e44242986c6495b139ec3d5bdc/mechanics/RELEASE-VERSIONING-PRINCIPLES.md

### CODE REVIEW

**Review by evankanderson — COMMENTED** [review]
/lgtm
/approve

Do you want me to try to fill out a month or two of these?

**Comment by dprotaso** [comment]
> Do you want me to try to fill out a month or two of these?

If you'd like - I'm also planning on update the the release steps in `knative/release` to say _"make sure these tables are up to date"_ prior to the release being cut

**Pull request merged**
