### PR TITLE
Add hh to Knative GitHub Org as a Member

### PR DESCRIPTION
**Pull request by hh**
See https://knative.slack.com/archives/CCSNR4FCH/p1650581831685649?thread_ts=1649809077.370369&cid=CCSNR4FCH

### CODE REVIEW

**Comment by csantanapr** [comment]
Hi @hh 
the test is failing because you need to regenerate owner alias file, please run this script https://github.com/knative/community/blob/main/hack/update-codegen.sh from the root directory

**Comment by evankanderson** [comment]
The actual error is:

```
Configuration failed: failed to configure knative members: users in both roles: hh
```

Do you need to be a GitHub admin, or just an org member?

**Comment by evankanderson** [comment]
You also need to join the org (and accept the invite) before we can add you to any of the Working Group GitHub groups -- a non-org member can't be a member of a team, and Peribolos backs off it's dry-run as soon as it sees a single error from GitHub.

**Pull request merged**
