### PR TITLE
Automate creation of OWNERS_ALIASES

### PR DESCRIPTION
**Pull request by evankanderson**
Automate generation of OWNERS_ALIASES. I deliberately tried to contain the `go.mod` 
blast radius to a small directory; similarly, I tried to have simple code for a 
simple feature. Happy to expand if desired/needed.

Will be followed up by a PR to http://github.com/knative-sandbox/knobots to enable 
copying `OWNERS_ALIASES` (and possibly other community files) to knative repos that 
get automation. (Another TODO: automate the addition of automation in knobots for new 
repos.)

/kind cleanup

### CODE REVIEW

**Comment by evankanderson** [comment]
(will need someone from steering to approve `OWNERS_ALIASES`)

**Comment by evankanderson** [comment]
Hmm, seems like @ronavn needs to accept his GitHub invite...

**Comment by evankanderson** [comment]
/retest

Ron accepted the invite

**Comment by evankanderson** [comment]
/assign @vaikas 

Oops, I thought I'd assigned Ville earlier, but my memory was faulty

**Comment by evankanderson** [comment]
It looks like Ron got removed from the organization again somehow...

**Comment by evankanderson** [comment]
It turns out that when Ron moved from Steering to Trademark, he was removed from the `admin` list, but wasn't moved to the `member` list, so he's being removed by Peribolos on each run, then re-invited.

**Review by vaikas — APPROVED** [review]
/lgtm

**Pull request merged**
