### PR TITLE
Add chzhyang to kperf approvers

### PR DESCRIPTION
**Pull request by chzhyang**
# Changes
- Adding chzhyang as an approver for the knative-sandbox/kperf repo

My contributions to Kperf could be found here: https://github.com/knative-sandbox/kperf/pulls?q=is%3Apr+is%3Aclosed+author%3Achzhyang, including:
  - Added the load command to kperf
  - Added config file support to kperf
  - Bug fixes
  - PRs review

I will continue to enhance kperf in the future.

/cc @maximilien @psschwei

### CODE REVIEW

**Review by maximilien — APPROVED** [review]
/approve
/lgtm

**Review by psschwei — COMMENTED** [review]
/lgtm

**Pull request merged**
