### PR TITLE
Add Paul Schweigert as docs approver (docs-writer)

### PR DESCRIPTION
**Pull request by csantanapr**
We understand that @psschwei is a great candidate to be an approver for [docs git repository](https://github.com/knative/docs).  

The DUX Working Group would like to nominate @psschwei to be an approver and understand that it meets all the [requirements](https://github.com/knative/community/blob/main/ROLES.md#requirements-1) stated in our governance documentation for [ROLES](https://github.com/knative/community/blob/main/ROLES.md). 

- [x] Reviewer of the codebase for at least 3 months.
- [x] Primary reviewer for at least 10 substantial PRs to the codebase.
@psschwei submitted the following PRs in the last 3 months (12):
1. knative/docs#4285
1. knative/docs#4260 
1. knative/docs#4299
1. knative/docs#4298
1. knative/docs#4333
1. knative/docs#4409
1. knative/docs#4412
1. knative/docs#4413
1. knative/docs#4431
1. knative/docs#4391
1. knative/docs#4442
1. knative/docs#4416

@psschwei have reviewed the following PRs in the last 3 months (13)
1. knative/docs#4194
2. knative/docs#4428
3. knative/docs#4434
4. knative/docs#4435
5. knative/docs#4486
6. knative/docs#4517
7. knative/docs#4539
8. knative/docs#4544
9. knative/docs#4565
10. knative/docs#4566
11. knative/docs#4572
12. knative/docs#4577
13. knative/docs#4578

- [x] Nominated by a WG lead (with no objections from other leads).
Was discussed to nominate Paul to be an approver of docs git repo by DUX WG leads (@csantanapr and @snneji ) during the DUX WG meeting on 2021-12-13. There were no objections in DUX WG Meeting. See agenda and recording for more details https://docs.google.com/document/d/1NSlGHen5Dh6c2A0LGavGWibddWrlSLV_PbEbMpNjSTU/edit

### CODE REVIEW

**Comment by julz** [comment]
\o/

lgtm from a "should Paul be an approver in docs" pov.

I wonder from a process point of view if we should rewrite the approver requirements for docs / note explicitly somewhere that docs doesn't follow the standard process and what process it does follow (assuming it doesn't - and probably shouldn't - follow the standard process in https://github.com/knative/community/blob/main/ROLES.md#requirements-1). It'd be good to be clear when we are/aren't following those criteria in a particular area etc to avoid the appearance that we're either not following or not documenting the rules.

**Comment by csantanapr** [comment]
/hold
Paul will be nominated at the TCO weekly meeting, if the TOC approves then we can move forward to merge this.

**Comment by csantanapr** [comment]
@julz I updated the main comment with more information about meeting the requirements.

**Comment by csantanapr** [comment]
cc @snneji

**Comment by snneji** [comment]
@csantanapr I just looked at the files changed and I didn't see Paul added. Could you take a look?

**Comment by csantanapr** [comment]
>@csantanapr I just looked at the files changed and I didn't see Paul added. Does another line need to be added here?

@snneji duh yes! I did the clean-up and forgot to add Paul. Is added now 👍 thanks for the review

**Comment by rhuss** [comment]
+1 from my side

**Comment by evankanderson** [comment]
This shouldn't need TOC approval (except for the unfortunate situation that these files require TOC approvers).

**Review by evankanderson — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
