### PR TITLE
Removing Sam as Doc WG lead

### PR DESCRIPTION
**Pull request by RichieEscarez**
Sam stopped working on the project some time in March.

### CODE REVIEW

**Comment by RichieEscarez** [comment]
assign/ @abrennan89

**Comment by mattmoor** [comment]
Hey @RichieEscarez, welcome back.  Sorry to hear that @samodell might not come back, I hope she's doing better.

The process for new working group leads is spelled out [here](https://github.com/knative/community/blob/master/ROLES.md#role-summary), and the PRs adding new leads are generally asked to follow a form like [this](https://github.com/knative/community/pull/99).  I think the idea of "replacing" WG leads sets a bad precedent, so I'd prefer if we removed Sam separately from the process above.

I don't think the quantitative aspects of our WG lead "template" cover  everything though, especially prolonged absence.  I think I'd personally be more comfortable if the bulk of the contributions justifying WG leadership had a bias towards recent contribution because in that role the importance of context is fairly high.

**Comment by RichieEscarez** [comment]
Thanks Matt! Sam is definitely off the project. She is back to being "Sam" but decided to move back into working on GCP products rather than OSS.

Sounds good (to just removing Sam in this PR). My motivation here had two parts. I added this to todays Docs WG meeting with the intention to discuss this there but given the lack of sessions and attendance (today and through Aug), I knew that I would/could get input/feedback this route.

Question: Given the two lead definitions, my goal was to try and help fulfill the expectations listed. I know much as changed since the beginning of the year especially in the Docs WG and many formal WG processes seem not to exist or are lacking an owner. That type of support is not articulated in the community guidelines so I'm wondering if it would be considered?

Also, regarding "absence", that's not spelled out either? I did ramp down significantly but was still an active member over Q2 and Q3. That said, the scope of time for someones contributions are also lacking in the community guidelines (does that mean I still can check all the boxes)? Anyway, ill try again and bring up whether I should fill out the Docs WG lead from in the next Docs meeting.

**Comment by evankanderson** [comment]
Welcome back @RichieEscarez !

I agree with Matt that making this two PRs will be clearer, and I'm sorry to hear that we won't be seeing Sam again.

Given your previous time with the project, I'd expect that you'd probably be quickly contributing effectively as a WG lead -- I'd defer decision on the nomination to @abrennan89 , who has been trying to right the process ship that slipped during the time when there was no WG lead.

I'd advise her to sit down with you and make sure that you two have the same vision and goals (possibly by working together for at least a few weeks) before adding a second WG lead. Having an extra set of hands to bail out a boat can be helpful, unless you each end up bailing into each others' boats (i.e. working at cross-purposes). Working together for a few weeks and planning out what the next few months look like should help both of you figure out if it's a good fit, since I know Ashleigh has a few opinions about what her ideal stack would look like.

**Review by evankanderson — COMMENTED** [review]
/lgtm
/approve

Since this is a pure removal.

I can follow up with a PR for peribolos.

**Pull request merged**
