### PR TITLE
Add myself as a candidate for Steering Election

### PR DESCRIPTION
**Pull request by xtreme-sameer-vohra**
# Changes
-  add myself as a candidate for Steering Election

### CODE REVIEW

**Comment by jberkus** [comment]
Oooh, we get to test whether we have a bug in my GH-handle-parsing code!

Sameer Vohra meets the qualifications to run for Steering Committee.

/lgtm
/approve

**Comment by gabo1208** [comment]
+1 to Sameer!

**Comment by sabbyanandan** [comment]
+1 to @xtreme-sameer-vohra; he's a rockstar! 💪🏾

**Pull request merged**
