### PR TITLE
Update leads for Operations WG.

### PR DESCRIPTION
**Pull request by k4leung4**

### CODE REVIEW

**Comment by k4leung4** [comment]
/cc @isdal 

Both Greg and Jessie have left their corresponding roles as leads

**Comment by bbrowning** [comment]
Just to document it here, I agree with adding Vincent as an Operations WG lead to replace Greg.

**Comment by isdal** [comment]
@evankanderson @mattmoor @vaikas per the TOC meeting today I believe we need you fine folks to sponsor Vincent and Chao before I can approve.
https://knative.dev/contributing/roles/#lead

**Comment by bbrowning** [comment]
As far as meeting the lead criteria, here are the stats for Vincent:

`Recognized as having expertise in the group's subject matter.` - yes

`Approver for some part of the codebase for at least 3 months.` - yes

`Member for at least 1 year or 50% of project lifetime, whichever is shorter.` - yes

`Reviewed or merged at least 50 PRs.` - I did this manually, but I counted 39 authored PRs and at least 12 reviewed PRs.

`Primary reviewer for 20 substantial PRs`. - I don't know the best way to quantify substantial. I did count 12 non-trivial (but perhaps not substantial?) PR reviews for the above metric. Do we have an automated way to determine this?

**Comment by vagababov** [comment]
I think historically we counted L, XL and XXL PRs as substantial

**Comment by mattmoor** [comment]
Probably worth doing the same documentation for @chaodaiG's satisfaction of the criteria above.  cc @adrcunha

**Comment by k4leung4** [comment]
Updated PR to update only Operations lead.

ptal

**Comment by adrcunha** [comment]
> Probably worth doing the same documentation for @chaodaiG's satisfaction of the criteria above. cc @adrcunha

Done: https://github.com/knative/community/pull/50

**Comment by k4leung4** [comment]
friendly ping
/cc @isdal

**Comment by isdal** [comment]
/lgtm
/approve

(same for #50, thanks for splitting them out)

**Comment by evankanderson** [comment]
A bit late, but:

/approve

**Pull request merged**
