### PR TITLE
Remove tcnghia from TOC doc and corresponding Peribolos

### PR DESCRIPTION
**Pull request by tcnghia**
# Changes

- :broom: Remove tcnghia from TOC doc and corresponding Peribolos

/kind cleanup

Fixes #

**Release Note**

```release-note
NONE
```

**Docs**

```docs
NONE
```

### CODE REVIEW

**Comment by tcnghia** [comment]
@mattmoor I am not sure what this error means 

```
{"component":"unset","file":"prow/cmd/peribolos/main.go:202","func":"main.main","level":"fatal","msg":"Configuration failed: failed to configure knative members: users in both roles: rhuss","severity":"fatal","time":"2021-02-15T19:51:44Z"}
```

**Comment by rhuss** [comment]
@tcnghia thanks for taking care !

I suspect that you have to remove `rhuss` from the `members:` section and add yourself instead (but please mind the alphabetical order).

Looks like you can be either in the `admin` or `members` section.

**Comment by tcnghia** [comment]
@rhuss thanks! done now.

**Review by mattmoor — APPROVED** [review]
/lgtm

thanks for everything @tcnghia 😢  Welcome @rhuss! 🎉

**Comment by mattmoor** [comment]
/cc @knative/steering-committee 
/assign @vaikas @bsnchan @pmorie 

Need steering b/c it touches files at root of the repo.

**Comment by rhuss** [comment]
Thanks for everything you've done for the community @tcnghia!

**Comment by bsnchan** [comment]
Thanks for all your contributions @tcnghia!

/approve

**Pull request merged**
