### PR TITLE
Changing deprecated functions in ./hack/update-codegen.sh

### LINKED ISSUE #1278: Remove deprecated functions in ./hack/update-codegen.sh
```ioutils``` is a deprecated package with all its functionality possible by ```io``` or ```os``` packages. We need to replace the required deprecated functions with alternatives.

### PR DESCRIPTION
**Pull request by Bisht13**
# Changes

- :broom: Change deprecated functions for reading and writing a file
- 🗑️ Remove ```io/ioutil``` import

/kind cleanup

Fixes #1278

### CODE REVIEW

**Comment by psschwei** [comment]
While you're at it, could you also get this one? https://github.com/knative/community/blob/62d1cf134b43d7302a5f9ed5963d14d74299615e/groups/reconcile.go#L342

**Comment by Bisht13** [comment]
> While you're at it, could you also get this one?
> 
> https://github.com/knative/community/blob/62d1cf134b43d7302a5f9ed5963d14d74299615e/groups/reconcile.go#L342

Done ✨

**Review by psschwei — COMMENTED** [review]
Thanks for the PR @Bisht13 !!

/lgtm
/approve

**Pull request merged**
