### PR TITLE
Change min K8s version to reflect reality

### PR DESCRIPTION
**Pull request by dprotaso**
- 0.14 min K8s is 1.15
- 0.15 min K8s is 1.16
- 0.16 min K8s will remain 1.16
- 0.17 min K8s will hopefully be 1.17

Delay is due to availability of stable newer version from providers

I didn't bother predicting 0.18 and beyond

### CODE REVIEW

**Comment by dprotaso** [comment]
summoning TOC
/assign evankanderson grantr markusthoemmes mattmoor tcnghia

**Comment by dprotaso** [comment]
> Is this just pessimism, or based on actual product announcements?

```
0.14 min K8s is 1.15
0.15 min K8s is 1.16
```

These are amendments to reflect what we supported when we released.


```
0.16 min K8s will remain 1.16
```


AKS - [Kubernetes version 1.17 will GA on the week of July 1st](https://github.com/Azure/AKS/releases/tag/2020-06-15)
GKE - 1.17 is still in the rapid channel
EKS - [1.17 has no release date ](https://github.com/aws/containers-roadmap/issues/697)

Given the lack of availability of 1.17 for the upcoming release I revised it to 1.16.

```
0.17 min K8s will hopefully be 1.17
```

The original release is had K8s min version 1.18 - I'm being pessimistic that version will be available


> If we're diverging from the kubernetes upstream release min version, we might also want to update the principles mentioned earlier to call out that we are blocking on one or more of AKS, EKS and GKE.

I can bring this up in the ToC meeting to get input but I agree that we need some revisions

**Comment by evankanderson** [comment]
From Tim Pepper on slack:

> k8s community patch backport support is going to be “one year” (for 1.19 and newer) instead of the previous fuzzy “until the 3rd newer release comes out” which tended to give an strange 9 months (or more?  or less?) of patch support depending confusingly on the future project’s release dates

I'm willing to approve this for now with an item to come back and update the principles as the K8s community evolves their rules.

**Pull request merged**
