### PR TITLE
Remove old copy of docs' CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by evankanderson**
Per discussion in https://github.com/knative/docs/pull/3269#issuecomment-786832305, it seems like the copy of `DOCS-CONTRIBUTING.md` in community is less up-to-date than the copy in the actual docs repo. It seems like people working on documentation mostly looked in the repo itself to find the content, so link there and retire this document.

Still TODO: copy over the new page template if needed and retire the directory entirely.

# Changes

- 🧹 🗑️  `DOCS-CONTRIBUTING.md`, which is outdated compared with the top-level `CONTRIBUTING.md` in the docs repo.
/kind cleanup documentation

/assign @RichieEscarez

### CODE REVIEW

**Comment by RichieEscarez** [comment]
Replacing /community file with the /docs files = LGTM. This was being done here too: https://github.com/knative/docs/issues/2960

There are other files that link to this file you are removing so the 404s/broken links must be addressed, ie https://knative.dev/community/contributing/docs/

You can add an aliases entry to the frontmatter in the /docs file you want to replace this with, but all links in GitHub are hardcoded will point to a missing file (so clicking on a link in GitHub will 404). Best practice is to sweep both repos for hadecoded links and replace them all (but adding the frontmatter redirect will fix the site if this file is deleted).

**Comment by evankanderson** [comment]
> There are other files that link to this file you are removing so the 404s/broken links must be addressed, ie https://knative.dev/community/contributing/docs/

I think that particular file is actually in this PR.


> You can add an aliases entry to the frontmatter in the /docs file you want to replace this with, but all links in GitHub are hardcoded will point to a missing file (so clicking on a link in GitHub will 404). Best practice is to sweep both repos for hadecoded links and replace them all (but adding the frontmatter redirect will fix the site if this file is deleted).

I added a redirect to website: https://github.com/knative/website/pull/257

There was one other reference on the website, which I added to https://github.com/knative/docs/pull/3269, which I think we can submit _before_ this PR if we want.

Or, we can submit the website redirect (257) and then this PR without needing to submit 3269.

**Comment by evankanderson** [comment]
/approve

(because we disabled auto-approve)

**Review by maximilien — APPROVED** [review]
/lgtm

**Review by RichieEscarez — APPROVED** [review]
/lgtm

**Pull request merged**
