### PR TITLE
Adding skonto as 2022 TOC candidate

### PR DESCRIPTION
**Pull request by skonto**
Hello all, I am Stavros Kontopoulos!

I have been working on the Knative project in various areas for two years now.
I spend my time on Knative Serving but also on cross-cutting concerns like observability, networking etc.
I am also interested in making users successful with Knative thus I have contributed in different aspects such as
debugging issues, reviewing PRs, adding documentation and features. 

I would like to see the project becoming even more successful and I am interested a lot in helping
to that direction eg. grow our community. I feel there is space for improvement for the many sub-projects we maintain to make Knative the best solution for Cloud Native application development.

Giving a shot! :)

### CODE REVIEW

**Comment by geekygirldawn** [comment]
/hold
To avoid merging until people provide feedback.

The criteria for running for the TOC is "Current TOC members and Approvers with at least 3 months tenure are eligible to stand for election." I see that you are a reviewer, but I'm not seeing any approver roles, so I'm not sure that you're eligible?

**Comment by jberkus** [comment]
Steering Committee:

Stavros is an approver on two Sandbox projects.  We need an official ruling by steering on whether sandbox projects count for eligibility.

**Comment by lance** [comment]
> Steering Committee:
> 
> Stavros is an approver on two Sandbox projects. We need an official ruling by steering on whether sandbox projects count for eligibility.

These requirements were discussed in the TOC meeting today. The notes from that meeting state:

> Upcoming TOC election
> Currently, TOC candidacy requires being an approver. But we don’t currently have a good / quick path to approver, and lots of participants don’t get the “approver” bit.
> Since these are governance documents, do we need steering to approve changing the bar?
> Do we need an exception process for the approver requirement 
> Currently requires 3 months of approver, maybe should change to 6 months member of the project and a current approver.

This is a TOC discussion that I suppose would need to be formalized by SC. /cc @csantanapr @thisisnotapril @vaikas @pmorie @itsmurugappan @evankanderson

**Comment by vaikas** [comment]
I'm little confused about what the proposed change is:
```
maybe should change to 6 months member of the project and a current approver
```

But isn't that exactly what it says above?
```
Currently, TOC candidacy requires being an approver.
```

@skonto has mosdef been a member for >6 months already, so that change doesn't matter here. @lance can you clarify?

Reading the between he lines I think what's maybe being proposed that being an approver in a sandbox repo would meet the criteria.

**Comment by csantanapr** [comment]
My take is that `knative-sandbox` repos are as important as the ones in `knative` both git orgs should be treated equally

**Comment by evankanderson** [comment]
> I'm little confused about what the proposed change is:
> 
> ```
> maybe should change to 6 months member of the project and a current approver
> ```
> 
> But isn't that exactly what it says above?
> 
> ```
> Currently, TOC candidacy requires being an approver.
> ```
> 
> @skonto has mosdef been a member for >6 months already, so that change doesn't matter here. @lance can you clarify?
> 
> Reading the between he lines I think what's maybe being proposed that being an approver in a sandbox repo would meet the criteria.

https://github.com/knative/community/blob/main/TECH-OVERSIGHT-COMMITTEE.md doesn't list any requirements for TOC membership, but does link to https://github.com/knative/community/blob/main/mechanics/TOC.md explaining how the TOC is elected. In that document, it says:

<a href="https://github.com/knative/community/blob/main/mechanics/TOC.md#candidate-eligibility">
> Current TOC members and [Approvers](https://github.com/knative/community/blob/main/ROLES.md#approver) with at least 3 months tenure are eligible to stand for election.]
</a>

Which I think most people have taken to mean "you have been an approver for at least 3 months". In turn, Approver is defined in [ROLES.md](https://github.com/knative/community/blob/main/ROLES.md#approver), and suggests that it involves "being in an OWNERS file", but doesn't explicitly indicate whether `knative-sandbox` contributions count in this case.

**Comment by jberkus** [comment]
What we were asking for clairfication on is whether or not Sandbox counts for the Approver requirement.  It is unstated in the current rules, which is why we need Steering to confirm that Sandbox also qualifies people.

**Comment by vaikas** [comment]
Perfect, thanks, yeah, I was trying to boil the mod to smallest piece and it sounded to me like that was what was being asked and if so, I totally agree that Sandbox should qualify people.

**Comment by geekygirldawn** [comment]
Hi @skonto - no need to withdraw your nomination! These questions came up because the criteria were unclear, and they uncovered some things that we hadn't thought about before. This is a healthy part of the process and will result in us improving some of our documentation :) 

So far, we have 3 SC members who have chimed in to support Knative Sandbox approvers as qualified for the TOC, so I'm going to wait another day or so to make sure none of the others object before we approve your candidacy.

**Comment by vaikas** [comment]
@skonto precisely what @geekygirldawn said :) We need to just update our docs / processes, so thanks for bearing with us while we go through this! :)

**Comment by skonto** [comment]
Ok thank you all!

**Comment by itsmurugappan** [comment]
my take is approvers of Knative Sandbox repos should be eligible for running for TOC

**Comment by geekygirldawn** [comment]
We now have 4 SC members agreeing that approvers for Sandbox projects counts toward TOC eligibility with Murugappan's last comment, so @skonto meets the qualification as a candidate. @skonto thank you so much for your patience as we worked through this process!

**Pull request merged**
