### PR TITLE
add xiangpingjiang to knative and knative-extensions

### PR DESCRIPTION
**Pull request by xiangpingjiang**
# Changes

I'm adding myself as a knative and knative-sandbox member so I don't need to wait for  the `ok-to-test` labels.

My contributions so far have been:
[eventing](https://github.com/knative/eventing/commits?author=xiangpingjiang)
[client](https://github.com/knative/client/commits?author=xiangpingjiang)
[docs](https://github.com/knative/docs/commits?author=xiangpingjiang)
[serving](https://github.com/knative/serving/commits?author=xiangpingjiang)

cc @Cali0707  @creydr @dsimansk

<!--
In addition, categorize the changes you're making using the "/kind" Prow command, example:

### CODE REVIEW

**Comment by Cali0707** [comment]
LGTM from my side!

/cc @pierDipi

**Review by pierDipi — COMMENTED** [review]
/lgtm
/approve

**Comment by creydr** [comment]
LGTM from my side too. Thanks a lot for your contributions on the OIDC work @xiangpingjiang so far!

/lgtm

**Comment by Leo6Leo** [comment]
That's so amazing! Thanks for all the work you have done @xiangpingjiang , so happy for you!

**Pull request merged**
