### PR TITLE
Add definitions of alpha/beta/GA to maturity levels

### LINKED ISSUE #144: Define criteria for different API maturity levels / API conventions
In many places we refer to "alpha", "beta", and "stable" or "GA" API levels, but these are not formalized anywhere. We should explicitly define the properties of these different levels and criteria that must be met to be considered a particular level.

Closely related to the concept of API maturity levels is having clear API conventions that must be followed so that APIs within the ecosystem "feel" consistent and meet user expectations; we should also clearly define conventions for our APIs.

### PR DESCRIPTION
**Pull request by psschwei**
Fixes #144 

# Changes

Adds definitions of alpha / beta / GA for components / features / extensions to the maturity levels doc.

Definitions are taken from: https://github.com/knative/docs/blob/main/docs/serving/configuration/feature-flags.md#lifecycle

cc @knative/technical-oversight-committee

### CODE REVIEW

**Comment by krsna-m** [comment]
:+1:

**Review by matzew — COMMENTED** [review]
LGTM

**Comment by evankanderson** [comment]
Is this waiting on any further approval?

/approve

**Comment by davidhadas** [comment]
+1

**Comment by dprotaso** [comment]
/lgtm

not holding since we have quorum

**Pull request merged**
