### PR TITLE
Adds details to TOC elections about company limitations

### PR DESCRIPTION
**Pull request by bsnchan**
# Changes

Clarifies company limitations in the TOC elections process

/kind documentation

### CODE REVIEW

**Comment by bsnchan** [comment]
@googlebot I signed it!

**Comment by bsnchan** [comment]
@googlebot I signed it!

**Comment by bsnchan** [comment]
cc @knative/steering-committee

**Comment by evankanderson** [comment]
/lgtm

if needed. Someone from steering (including @bsnchan ) would need to `/approve`

**Review by thisisnotapril — APPROVED** [review]

**Pull request merged**
