### PR TITLE
Remove my old github username from the voters file

### PR DESCRIPTION
**Pull request by devguyio**
I've renamed my github username from Abd4llA to devguyio . This is a proof https://github.com/cncf/gitdm/pull/398

### CODE REVIEW

**Review by evankanderson — COMMENTED** [review]
/lgtm

I'll leave it to the elections committee to approve

**Comment by jberkus** [comment]
@devguyio can you fill out the Exceptions form so that we have your correct email address as well?  Thanks.

https://bit.ly/knative-sc20-exception

Correction approved

**Comment by devguyio** [comment]
@jberkus done

**Comment by devguyio** [comment]
@evankanderson I think this is okay to approve?

**Comment by evankanderson** [comment]
I actually don't have OWNERS here, AFAIK.

/approve

Someone in the right file will need to put that comment in, though.

**Pull request merged**
