### PR TITLE
Add my candidacy for steering committee for 2023-2024

### PR DESCRIPTION
**Pull request by evankanderson**

### CODE REVIEW

**Comment by ReToCode** [comment]
I've confirmed that @evankanderson is [eligible as a candidate](https://github.com/knative/community/blob/main/mechanics/SC.md#candidate-eligibility) for the SC election.

I also looked at the format of the candidate file, and it looks good to me.

cc @geekygirldawn

**Comment by ReToCode** [comment]
Ah, @evankanderson can you rename the file to `candidate-evankanderson.md` to match your GH handle?

**Comment by csantanapr** [comment]
THANK YOU @evankanderson 🙏 for nominating, 
I think I can sale publicly I endorse this candidate  👍

**Pull request merged**
