### PR TITLE
add myself as member

### PR DESCRIPTION
**Pull request by hueifeng**

### CODE REVIEW

**Comment by csantanapr** [comment]
Hi @hueifeng 

Please refer to the [member](https://github.com/knative/community/blob/main/ROLES.md#member) ROLE and state in your first comment how you meet the requirement and the type of contributions you have made to Knative.

**Comment by hueifeng** [comment]
@evankanderson It looks like the `do-not-merge/hold` label cannot be automatically merged.

**Comment by zroubalik** [comment]
> @evankanderson It looks like the `do-not-merge/hold` label cannot be automatically merged.

@hueifeng could you please address the https://github.com/knative/community/pull/1099#issuecomment-1158337234 by Carlos?

**Pull request closed without merging**
