### PR TITLE
Add proposed format for emeritus for TOC

### PR DESCRIPTION
**Pull request by vaikas**
As discussed in #626 wanted to put a possible format for TOC for discussion. If this is aok, I'll make these changes elsewhere as well.

-
-
-

/kind <kind>

Fixes #

**Release Note**

```release-note

```

**Docs**

```docs

```

### CODE REVIEW

**Review by julz — APPROVED** [review]
Nice. Love this ❤️ 

/lgtm
/hold just to give people time to bike shed if anyone wants to, but @vaikas feel free to unhold whenever you like as far as I'm concerned

**Comment by vaikas** [comment]
The one reason I left out the company affiliation is because for some folks it has changed since they left, changed while the folks were serving, etc. and would've complicated things for no benefit that I could see.

**Comment by julz** [comment]
> The one reason I left out the company affiliation is because for some folks it has changed since they left, changed while the folks were serving, etc. and would've complicated things for no benefit that I could see.

I guessed that was why, fwiw, and it makes sense to me

**Comment by bsnchan** [comment]
/approve

Thanks for doing this <3 !

**Comment by csantanapr** [comment]
❤️ this idea @vaikas +1

**Comment by vaikas** [comment]
Ok, I think it's been long enough for folks to comment. We can always change things later as we see fit.
/unhold

**Pull request merged**
