### PR TITLE
Update the new-repo instructions

### PR DESCRIPTION
**Pull request by mattmoor**
/hold

HOLD until everything else has been confirmed.

Fixes: https://github.com/knative/community/issues/298

### CODE REVIEW

**Review by n3wscott — COMMENTED** [review]
/lgtm
/approve

**Comment by mattmoor** [comment]
/assign @bsnchan @thisisnotapril @pmorie 

Need and adult, err...  OWNER 😉

**Review by thisisnotapril — APPROVED** [review]

**Comment by thisisnotapril** [comment]
Not sure I fully qualify as an "adult" but approved! 🤣

**Pull request merged**
