### PR TITLE
Add client-pkg to knative for code shared between `kn` and its plugins

### PR DESCRIPTION
**Pull request by rhuss**
This will also hold the reusable CLI API which can be leveraged
by other projects for simplified access to Knative (adding
also some enhancements like 'wait to be ready' and also some
knative specific logic)

# Changes

This PR updates the peribolos configuration to add a `client-pkg` repository to the  `knative` GitHub organisation.

### CODE REVIEW

**Review by maximilien — APPROVED** [review]
/approve
/lgtm

**Comment by markusthoemmes** [comment]
/hold

I believe we agreed to not do this. Holding to prevent an accidental merge.

**Comment by vaikas** [comment]
Since #704 got merged, I think this can be closed?
@rhuss is that correct?

**Comment by rhuss** [comment]
has already been included, closing ...

/close

**Pull request closed without merging**
