### PR TITLE
Krsna step down

### PR DESCRIPTION
**Pull request by krsna-m**
Was a pleasure working with all of you!

### CODE REVIEW

**Comment by dprotaso** [comment]
cc @knative/technical-oversight-committee

**Comment by dprotaso** [comment]
@knative/steering-committee you need to approve the change

**Comment by dprotaso** [comment]
Thanks for all your contribution Krsna

**Comment by dsimansk** [comment]
Thanks a lot! Best of luck in your next thing.

**Comment by psschwei** [comment]
Thanks for all your contributions Krsna and best of luck in what comes next!

**Comment by nainaz** [comment]
Thank you Krsna!
All the best for he future endeavors!
Thank you,
-N

**Comment by dprotaso** [comment]
can someone form steering `/approve` the PR

**Pull request merged**
