### PR TITLE
Updated Elekto results page with the final TOC election results

### PR DESCRIPTION
**Pull request by geekygirldawn**
Updated Elekto results page with the final TOC election results, since we are not having a runoff.

@jberkus Can you have a quick look to make sure that this looks good to you and doesn't break anything in Elekto before we have someone from steering approve it?

/hold

### CODE REVIEW

**Review by evankanderson — COMMENTED** [review]
/lgtm
/approve

We should have put you two in `/elections/2021-TOC/OWNERS` to simplify your workflow. Thanks for all your work!

**Comment by jberkus** [comment]
Looks good, please merge.

**Pull request merged**
