### PR TITLE
Update SC members and SC permissions

### PR DESCRIPTION
**Pull request by ReToCode**
The SC election results were [announced today](https://groups.google.com/g/knative-dev/c/oO8Xtw3i-Q4), this PR updates the relevant configurations.

# Changes
- Add @aliok and @evankanderson as new members
- Remove @lance and @csantanapr

Partially #1468

### CODE REVIEW

**Comment by geekygirldawn** [comment]
I think we're waiting for @aliok and @evankanderson to confirm that these are the emails they want to use in those files.

**Comment by aliok** [comment]
> are those your emails you would like to use?

Yes.

LGTM

Thanks

**Comment by dprotaso** [comment]
@lance can you `/approve`

**Comment by dprotaso** [comment]
looks like this needs a rebase @ReToCode

**Comment by dprotaso** [comment]
OK - I rebased

**Comment by lance** [comment]
ugh - needs rebase again

**Comment by dprotaso** [comment]
thanks everyone!

**Pull request merged**
