### PR TITLE
Archive plugin repositories without releases and current maintenainers

### PR DESCRIPTION
**Pull request by dsimansk**
# Changes

- Archive plugin repositories without releases and current maintenainers
  - knative-extensions/kn-plugin-diag
  - knative-extensions/kn-plugin-migration
 
For quiet some time there was no other changes then version bumps from our automation. It's time to archive the repos until there's new interest in those areas.

/cc @rhuss 
/cc @knative/technical-oversight-committee

### CODE REVIEW

**Comment by dsimansk** [comment]
Per #knative-client channel thread: https://cloud-native.slack.com/archives/C04LY4SKBQR/p1719912777029269

**Comment by dprotaso** [comment]
/lgtm
/approve

Can you also update the knobots configuration?

**Comment by dsimansk** [comment]
> /lgtm /approve
> 
> Can you also update the knobots configuration?

Yep, in the queue: https://github.com/knative-extensions/knobots/pull/396

**Pull request merged**
