### PR TITLE
Add myself to eventing-rabbitmq approvers

### PR DESCRIPTION
**Pull request by gvmw**

### CODE REVIEW

**Comment by gvmw** [comment]
It may be quicker if /assign @julz 

Want to start clearing these open PRs:
- https://github.com/knative-sandbox/eventing-rabbitmq/pull/522#issuecomment-979127478
- https://github.com/knative-sandbox/eventing-rabbitmq/pull/524#issuecomment-979128612

**Comment by gvmw** [comment]
/assign @julz
(may be quicker)

Want to start clearing these open PRs:
- https://github.com/knative-sandbox/eventing-rabbitmq/pull/522#issuecomment-979127478
- https://github.com/knative-sandbox/eventing-rabbitmq/pull/524#issuecomment-979128612

**Comment by evankanderson** [comment]
I'd love to get an "okay" from one of the existing approvers, at least for decorum / process.

@gvmw is a RabbitMQ committer who's been helping bring the RabbitMQ implementation up to speed.

**Comment by gvmw** [comment]
OK, that makes sense Evan.

Waiting for @benmoss @salaboy @xtreme-sameer-vohra to "okay".

**Comment by benmoss** [comment]
@gvmw can you run `hack/update-codegen.sh`?

**Comment by gvmw** [comment]
> @gvmw can you run `hack/update-codegen.sh`?

I think the best answer is: 😀

Serious answer is we need workflows that rely less on tribal knowledge and more on self-discovery. Imperfect as it is, this is my attempt to address it: https://github.com/knative-sandbox/eventing-rabbitmq/pull/525/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R241-R245

**Comment by gvmw** [comment]
I just realised that you meant running `hack/update-codegen.sh` in the context of this PR. The change made and the result of the build is astonishing to me.

**Comment by gvmw** [comment]
Back to you @evankanderson

**Review by evankanderson — COMMENTED** [review]
/lgtm
/approve

/assign @pmorie

**Pull request merged**
