### PR TITLE
Add SAP Event Mesh to ADOPTERS

### PR DESCRIPTION
**Pull request by travis-minke-sap**
# Changes

- 🎁  Add SAP Event Mesh to adopters list
- 🧹  Fix pre-existing whitespace alignment

/kind documentation

Previously commented on Issue #696 but not automated updates occurred - was directed to create a PR ; )

**Release Note**

**Docs**

### CODE REVIEW

**Review by rhuss — COMMENTED** [review]
Just out of curiosity, how does SAP Event Mesh leverages Knative ? When looking on the web page I can't find any reference to Knative, nor is there any hit when searching for Knative via https://help.sap.com/viewer/product/SAP_EM/Cloud/en-US?q=knative

I guess it's an internal implementation detail ? (but does not offer the Knative Eventin API to the end-user) ?

**Comment by travis-minke-sap** [comment]
> Just out of curiosity, how does SAP Event Mesh leverages Knative ? When looking on the web page I can't find any reference to Knative, nor is there any hit when searching for Knative via https://help.sap.com/viewer/product/SAP_EM/Cloud/en-US?q=knative
> 
> I guess it's an internal implementation detail ? (but does not offer the Knative Eventin API to the end-user) ?

Yeah, you are correct - it is in internal implementation detail that is not exposed to end users.  We currently only use **Eventing** and the _Distributed_ **KafkaChannel** implementation we contributed to Knative in a "Complex Delivery" pattern (no sources/brokers/trigger/etc).

**Pull request merged**
