### PR TITLE
Adding Naina Singh candidancy profile for SC elections

### PR DESCRIPTION
**Pull request by nainaz**
# Changes

-
-
-

/kind <kind>

Fixes #

**Release Note**

```release-note

```

**Docs**

```docs

```

### CODE REVIEW

**Comment by geekygirldawn** [comment]
@nainaz can you push a commit to remove the link after Red Hat for your affiliation? We usually just put the company name, no link.

**Comment by geekygirldawn** [comment]
I've confirmed that @nainaz meets the criteria to run for SC:
*Is an eligible voter in this election (confirmed in voters.yaml)
* Holds at least a project member role (is a reviewer for a couple of areas)

/hold
@jberkus to double check the format

**Comment by jberkus** [comment]
@nainaz please remove the URL from your Affiliation line.

/hold

**Comment by nainaz** [comment]
Done.
Please let me know if it is okay now

**Pull request merged**
