### PR TITLE
Remove emeritus WGs from Peribolos

### PR DESCRIPTION
**Pull request by aliok**
# Changes

- Remove emeritus WGs from Peribolos
-

/kind <kind>

Fixes #

**Release Note**

```release-note

```

**Docs**

```docs

```

### CODE REVIEW

**Comment by aliok** [comment]
@cardil @upodroid 

I am not 100% sure if the removed things are referenced in any repos. Can they be used in the OWNERS files in repositories? Or, do we manage those files based on the files here and this PR will be just fine?

**Review by cardil — APPROVED** [review]

**Comment by cardil** [comment]
> @aliok: I am not 100% sure if the removed things are referenced in any repos. Can they be used in the OWNERS files in repositories? Or, do we manage those files based on the files here and this PR will be just fine?

I think only OWNER_ALIASES is synched. The OWNERS file needs to be adjusted if those removed teams are used. IDK, if it will break Prow review suggestions, but I doubt it.

**Comment by aliok** [comment]
> The OWNERS file needs to be adjusted if those removed teams are used. IDK, if it will break Prow review suggestions, but I doubt it.

Do I need to go and check each repo to find out where these deleted teams are used? Or will it be "only" review suggestions that might be broken. If it is the latter, I would want to merge this PR and send an email to knative-dev asking folks to check their own repositories.

**Review by upodroid — APPROVED** [review]
We aren't using these WGs in OWNERS file.

https://github.com/search?type=code&q=org%3Aknative+OR+org%3Aknative-extensions+%28conformance-task-force-leads+OR+docs-wg-leads+OR+eventing-triage+OR+conformance-writers%29+AND+NOT+path%3AOWNERS_ALIASES+

/hold cancel

**Pull request merged**
