### PR TITLE
Adding omerbensaadon's candidacy

### PR DESCRIPTION
**Pull request by omerbensaadon**
-------------------------------------------------------------
name: Omer Bensaadon
ID: omerbensaadon
info:
  - affiliation: Independent (Github Employee)
-------------------------------------------------------------

## Contributions

* Execution Lead on the GA (1.0) Task Force
* Founded the User Experience Working Group w/ @csantana
* Led merging of Documentation and User Experience Working Groups
* Conducted interviews of ~30 end-users of Knative
* Led revamp of the Knative Website
* Authored the Knative Getting Started Guide
* Active member of the Knative Trademark Committee
* Introduced product practices, refinement, to many Knative processes (Roadmaps, namely)
* Product leadership on Knative Functions
* Helped connect end-users to Knative contributors (feedback, case study participants, ADOPTERS.MD)
* Many intangible contributions, like bringing stellar vibes to the table 💫

## Why I'm Running
This is an *extremely* exciting time to be involved with Knative. I would argue that the community is healthier and more aligned than it ever has been, and our best days are ahead of us.

If I may wax poetic for a second: what is the point of a Steering Committee, really? The way I see it, Steering is responsible for...
- Establishing community norms and values (what is and isn't OK in the eyes of the community?)
- Connecting end-users with the community at large (who does this community serve?)
- General community leadership (who do we trust to resolve things when things go wrong? Are unclear?)

I feel I have done my part to earn the trust of the many stellar members of this community and can effectively play these roles.

I also feel I bring proven experience to the table, with chops in developer experience, product thinking, marketing and effectively organizing contributors towards a share goal. Skillsets which I would argue are somewhat rare in the Knative Community.

On top of the above responsibilities, since I am going to be working at Github on Github Projects, I plan to participate in roadmap planning where I can (functionally dog-fooding my own product while contributing to Knative). Also, happy to take feature requests 😉.

I sincerely hope the members of the Knative community consider me a friend, a trusted ally and an effective leader in this community; regardless of who pays my salary.

### CODE REVIEW

**Comment by csantanapr** [comment]
+1 Omer, we need folks like Omer to grow the community in a healthy way

**Comment by salaboy** [comment]
@omerbensaadon work has been fundamental to get stuff done in a multi-company environment where coordination is needed to make sure that we all push in the same direction. +1

**Comment by psschwei** [comment]
+1 for Omer -- he's done tons of great things for the community

**Comment by xtreme-sameer-vohra** [comment]
+1 
I just wish this worked `git clone Omer`

**Comment by pmbanugo** [comment]
I like Omer's work in improving the UX for the project and improving the onboarding experience. 👍🏽

**Comment by matzew** [comment]
@omerbensaadon congratulations on moving to Github. 

However I am wondering if the new job will allow you to serve the Steering Committee in a proper way, given that Github (AFAIK) is not directly involved in Knative :thinking:

**Comment by lionelvillard** [comment]
> However I am wondering if the new job will allow you to serve the Steering Committee in a proper way, given that Github (AFAIK) is not directly involved in Knative

shush, his is our Trojan horse with the ultimate goal to have all GitHub events to be CloudEvents :-)

**Comment by nainaz** [comment]
+1 for the candidacy.

**Comment by omerbensaadon** [comment]
@matzew I've spoken with a few community leaders on this point, and after some deliberation have decided to run as an independent. 

**I've outlined what I feel the role of a Steering Committee member is and I fully believe I would be a stellar fit.** My leadership at Github (up to and including the new CEO) is supportive of Github employees participating in OSS. 

Also, I'm not sure we want to create a community whereby you must be employed by a vendor to participate in governance...

**Comment by omerbensaadon** [comment]
@lionelvillard gets it 😉

**Comment by gabo1208** [comment]
+1 for this candidacy!

**Comment by snneji** [comment]
+1 for Omer!

**Comment by csantanapr** [comment]
Looking forward to a future day when we publish a case study on how Github uses knative. And I come back to this issue to say, “Told you so.”

**Pull request merged**
