### PR TITLE
Update eventing-rabbitmq maintainers

### PR DESCRIPTION
**Pull request by dolfolife**
Add Eventing team at VMware to the RabbitMQ Eventing project

### CODE REVIEW

**Review by psschwei — CHANGES_REQUESTED** [review]
You'll need to update `peribolos/knative-sandbox.yaml` and then run `./hack/update-codegen.sh` to propagate your changes to the alias files

**Comment by psschwei** [comment]
/assign @pierDipi 
(assuming this should get sign-off from Eventing... )

**Comment by dolfolife** [comment]
more context: I have been working with @gabo1208 on the RabbitMQ broker and source and the team needs access to approve changes in the eventing-rabbitmq repo

**Review by gabo1208 — APPROVED** [review]

**Pull request merged**
