### PR TITLE
add homebrew-kn-plugins to knative-sandbox

### PR DESCRIPTION
**Pull request by rhuss**

### CODE REVIEW

**Review by maximilien — APPROVED** [review]
Nice thanks 🙏🏽 
/approve
/lgtm

**Review by maximilien — APPROVED** [review]
/approve
/lgtm

**Comment by rhuss** [comment]
closing this issue in favour of https://github.com/knative/homebrew-client/issues/18

**Comment by rhuss** [comment]
oops, didn't meant to close the PR

**Review by markusthoemmes — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
