### PR TITLE
Add self nomination for 2022 SC election

### PR DESCRIPTION
**Pull request by aslom**
# Changes

-
-
-

/kind <kind>

Fixes #

**Release Note**

```release-note

```

**Docs**

```docs

```

### CODE REVIEW

**Comment by geekygirldawn** [comment]
/hold
Need to verify eligibility and make sure the format is what Elekto expects.

**Comment by geekygirldawn** [comment]
I've confirmed that @aslom is eligible to run:
* Is an eligible voter in this election (confirmed in voters.yaml).
* Holds at least a project member role (is an project member and reviewer for Eventing)

@jberkus the format looks good to me, but given the disastrous results of the last merge, can you confirm that the format is what Elekto expects? If so, I think you can remove the hold and merge.

**Comment by jberkus** [comment]
Format is fine.

/remove-hold
/lgtm

**Pull request merged**
