### PR TITLE
Adding @puerco to calendar maintainers

### LINKED ISSUE #1265: [SC] Add new member Adolfo to steering committee
The following tasks need to be done 

- Add @puerco as new member
- Remove @itsmurugappan 

- [x] Add new member in [STEERING-COMMITTEE.md](https://github.com/knative/community/blob/main/STEERING-COMMITTEE.md)
- [x] [peribolos](https://github.com/knative/community/tree/main/peribolos) for both knative and knative-sandbox 
- [x] groups for mailing lists
  - https://github.com/knative/community/blob/main/groups/committee-steering/groups.yaml
  - https://github.com/knative/community/blob/main/groups/groups.yaml#L60
- [x] [CNCF Project maintainers](https://github.com/cncf/foundation/blob/main/project-maintainers.csv)
- [x] CNCF Knative Project JIRA access (via [cncf service desk](https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1) Jira ticket)
- [x] CNCF Knative maintainers group list (via [cncf service desk](https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1) Jira ticket)
- [x] New Blog post welcoming recent members @nainaz @salaboy @puerco to Steering Committee (Use [Example](https://knative.dev/blog/steering/2021-12-14-steering-elections-results/))

### PR DESCRIPTION
**Pull request by salaboy**
# Changes
- :gift: adding @puerco to calendar maintainers group

/kind enhancement

Partially addresses #1265

**Release Note**

```release-note

```

**Docs**

```docs

```

### CODE REVIEW

**Comment by lance** [comment]
Shouldn't @knative/steering-committee be among the approvers for knative/community?

**Comment by dprotaso** [comment]
/approve

@lance yeah can you update the OWNER file here and drop

https://github.com/knative/community/blob/087fb6d9da54ce7a3617e9a6855fafbe24043d02/groups/OWNERS#L7-L8

cc @upodroid

**Comment by upodroid** [comment]
I have updated the owners file in a separate PR.

**Comment by lance** [comment]
> I have updated the owners file in a separate PR.

Thanks @upodroid!

**Pull request merged**
