### PR TITLE
Removed docs contributing content from community

### PR DESCRIPTION
**Pull request by evankanderson**
This duplicates content in knative/docs:

https://github.com/knative/docs/blob/master/CONTRIBUTING.md
https://github.com/knative/docs/blob/master/new-page-template.md

OWNERS / README.md / _index.md were all artifacts to get these to render in the website, which doesn't seem necessary for contributor documentation.

### CODE REVIEW

**Comment by evankanderson** [comment]
/assign @abrennan89 @bsnchan 

Ashleigh, I think we want these docs in `knative/docs`, rather than here. What do you think?

**Comment by RichieEscarez** [comment]
The previous decision was that contribution info goes in Knative/Community, has that changed (sorry ive been away)?Thus, all contributing info is published here in the site (simply pull and publish that repo): https://knative.dev/community/ and aligns with all the other "how to contribute to Knative".

If content is removed from knative/community, where and how will it be published in the site (ie. how to show docs contribution guidelines under the "[contribution section](https://knative.dev/community/contributing/)")?

The docs template made sense living in knative/docs because its meant to be easily copied (ie. you dont need to clone /community or go make a copy of that template file).

I think maybe we should just update https://github.com/knative/docs/blob/master/CONTRIBUTING.md so that it instead points to the more recent knative/community stuff?

Im lost as to what "OWNERS / README.md / _index.md were all artifacts" refers to. Can you please clarify?

**Comment by RichieEscarez** [comment]
@evankanderson @abrennan89 ive come up with a solution to move "how-to" info to the knative/docs repo, keep the Knative member/contributor guidelines here in knative/community, and also use our existing infrastructure to simply create (copy a few files) a new `/authoring/` section. 

Details here https://github.com/knative/docs/issues/2960

WRT this PR, i think we should keep the `DOCS-CONTRIBUTING.md` here but reduced to only the "how to be a Knative doc member, workgroup info, and what the roles are" type info?

Also keep:
OWNERS - this is for github folder privileges so that docs members and approve and get prow to merge changes.
README.md - we could use this as a landing page to provide direction to look in `knative/docs/authoring' (or better yet, link to the knative.dev URL) for "docs authoring" info
_index.md - this is required for what Hugo calls a branch (a folder with multiple .md files) *[a Hugo leaf is a folder that contains only a single .md file and does not require the _index.md]*

**Comment by vaikas** [comment]
@evankanderson @abrennan89 @RichieEscarez Just a ping on this to see which parts of this are still relevant after the docs reshuffle and how should we proceed on this. This issue: https://github.com/knative/docs/issues/2960 would imply that there's some todo's there, but I'm unclear on the current state of affairs :)

**Comment by RichieEscarez** [comment]
This was made obsolete through knative/docs#2960 but its unclear what the information architecture is today with the move to mkdocs (ie where community content lives going forward). Currently, the previous community section continues to remain while the docs section has been redone: https://knative.dev/community/

**Comment by abrennan89** [comment]
+1 @RichieEscarez 

 cc @omerbensaadon @julz

**Pull request closed without merging**
