### PR TITLE
Switch to the 0.22 release leads

### PR DESCRIPTION
**Pull request by mattmoor**
/cc @evankanderson @markusthoemmes 
/assign @evankanderson @markusthoemmes 

/hold

Both have superpowers through TOC already, but I want both to ACK that they are on point for 0.22 per: https://github.com/knative/pkg/blob/master/RELEASE-LEADS.md#schedule

cc @lionelvillard (losing superpowers)

### CODE REVIEW

**Comment by evankanderson** [comment]
I think Markus is out this week, per Paul Morie.

**Comment by mattmoor** [comment]
He can approve when he's back.

/unhold

**Review by markusthoemmes — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
