### PR TITLE
Add myself to members in `knative.yaml` and `knative-sandbox.yaml`

### PR DESCRIPTION
**Pull request by debasishbsws**
# Changes

Add my GitHub username to members in `knative.yaml` and `knative-sandbox.yaml`

### CODE REVIEW

**Comment by aliok** [comment]
/lgtm
/approve

🎉

**Review by zroubalik — COMMENTED** [review]
@debasishbsws could you plese link here any existing contributions for a refence? Thanks 🙏

**Comment by debasishbsws** [comment]
@zroubalik Yes, sure.
- https://github.com/knative-sandbox/eventing-kafka-broker/pull/3006
- https://github.com/knative/docs/pull/5467
- https://github.com/knative-sandbox/eventing-kafka-broker/pull/3016
And I will also be contributing to Knative as a Mentee of GSoC'23 in the idea of https://github.com/knative-sandbox/eventing-kafka-broker/issues/2928

**Review by zroubalik — APPROVED** [review]
/lgtm
/approve


Welcome! 🎉

**Pull request merged**
